### ISSUE TITLE
Can it be replaced with socat?

### ISSUE THREAD

**Issue by KOLANICH** [getdnsapi/stubby#101]
Hello, could you explain if this can be replaced with socat which is a generic proxy which can be used for example to listen a tcp port and to wrap everything passing through it into tls. I mean
```
dig <-> udp or tcp:socat:tls <-> tls:dns server
```

**Comment by ArchangeGabriel** [comment]
You won’t achieve the same functionalities, but yes, before Stubby existing some people I know where running a socat between unbound and the upstream DNS-over-TLS server.

**Comment by KOLANICH** [comment]
@ArchangeGabriel could you write a chapter in the FAQ why can't it be replaced with socat and why do we need the functionalities missing?

**Comment by ArchangeGabriel** [comment]
You don’t /need/ them, depending on what you want to achieve. If you are just after DNS-over-TLS, Ubound going through socat or stunnel should be enough.

What I’m not sure of is wether you can have multiple upstream servers, pin spki for them, set ciphers/curves.

**Comment by KOLANICH** [comment]
>If you are just after DNS-over-TLS, Ubound going through socat or stunnel should be enough.

Thank you for the info.
