### ISSUE TITLE
Issue with running it on a Raspberry Pi

### ISSUE THREAD

**Issue by Zero3K** [getdnsapi/stubby#104]
I'm trying to use https://dns.cmrg.net/ with it on the Raspberry Pi. I am getting an error when doing so. The log is as follows:

[02:59:03.533929] STUBBY: 199.58.81.218 : ERROR: Hostname Authentication not available from TLS library (check library version)
 [02:59:03.534164] STUBBY: 199.58.81.218 : Conn closed: TLS - Resps= 0, Timeouts = 0, Curr_auth = Failed, Keepalive(ms)= 0 
[02:59:03.534208] STUBBY: 199.58.81.218 : Upstream : TLS - Resps= 0, Timeouts = 0, Best_auth = Failed [02:59:03.534238] STUBBY: 199.58.81.218 : Upstream : TLS - Conns= 0, Conn_fails= 1, Conn_shuts= 0, Backoffs = 0 [02:59:03.534333] STUBBY: FAILURE no valid transports or upstreams available!

By the way, does anyone know how it compares to Quad9/Cloudflare in terms of speed?

**Comment by saradickinson** [comment]
This error is generated if you are using OpenSSL earlier than 1.0.2 see the [getdns README](https://getdnsapi.net/documentation/readme/#building-and-external-dependencies). So you just need to update your OpenSSL to something later than that and rebuild stubby. 

As for the performance of https://dns.cmrg.net/ note that it is a single server based in North America so the latency will depend on where you are querying from. Whereas both Quad9 and Cloudflare run anycast services (with many PoP's around the globe) - Cloudfare make a point of saying they have a very low latency service and they do come top at[ dnsperf.com](https://www.dnsperf.com/).

**Comment by eccgecko** [comment]
I have a stupid question (I'm still learning): how exactly does one read the log for stubby? I have enabled the -l option in my systemd stubby.service file, and the daemon starts correctly, but I can't find any logs anywhere. I saw on the stubby web-page that logging is done via stderr, but how does one actually get at that? I;m rying to troubleshoot some issues with DNSSEC resolution, and I have a feeling it has to do with my dnsmasq config, but I want to narrow it down by checking my stubby log also

**Comment by ArchangeGabriel** [comment]
When debugging, I just launch stubby by hand.

**Comment by eccgecko** [comment]
Ah ok, will do. Thanks. So is there no way for stubby to output to a logfile? Or is it pointless when one can just run it manually?

**Comment by saradickinson** [comment]
@eccgecko Yes - stubby does log to stderr by default and depending on the platform that most probably gets sent to syslog already.  Or you can control it via the 'StandardError' item in the service file for example see  [view stdout/stderr of systed service](https://unix.stackexchange.com/questions/20399/view-stdout-stderr-of-systemd-service) and [systemd log redirect](https://stackoverflow.com/questions/37585758/how-to-redirect-output-of-systemd-service-to-a-file)

**Comment by saradickinson** [comment]
I'm closing this issue for now as it hasn't been updated in over a year - feel free to re-open if there are still questions
