### ISSUE TITLE
[Windows] Use relative path in “stubby.bat”

### ISSUE THREAD

**Issue by Kdmeizk** [getdnsapi/stubby#111]
For example, it will avoid strange results if the Stubby version in this folder is outdated (as I had when I did tests with the zipped version).

**Comment by saradickinson** [comment]
I prefer to leave the path as absolute because I think it will result in more, other strange results if not (e.g. the file won't be found...). But I have added a note to the webpage and README.txt to be clear that the paths are absolute.
