### ISSUE TITLE
Imprecision in example file

### ISSUE THREAD

**Issue by ArchangeGabriel** [getdnsapi/stubby#112]
At https://github.com/getdnsapi/stubby/blob/develop/stubby.yml.example#L120, it says that if you let this line uncommented, it will do zero-conf DNSSEC. But is that true even if getdns already has the key (because it is present at the default location)?

**Comment by wtoorop** [comment]
Indeed a documentation error.  Thanks for notifying!

Zero configuration DNSSEC will be triggered when validating in stub resolution mode and:
  - No root trust anchor could be found on the default *or* the configured location
  - The trust anchor at the default or configured location delivered a BOGUS root DNSKEY rrset

**Comment by saradickinson** [comment]
I think this is addressed by this commit? https://github.com/getdnsapi/stubby/commit/9a36ba9f150463b7360e3d7ed1f9f15806227e1e
