### ISSUE TITLE
question: interplay between dns_transport_list and tls_authentication?

### ISSUE THREAD

**Issue by monperrus** [getdnsapi/stubby#113]
I don't understand the interplay between configuration options `dns_transport_list` and `tls_authentication`.

* What are the valid options for `dns_transport_list` if `tls_authentication=GETDNS_AUTHENTICATION_REQUIRED`?
* What are the valid options for `dns_transport_list` if `tls_authentication=GETDNS_AUTHENTICATION_NONE`?

**Comment by ArchangeGabriel** [comment]
I agree that there is a confusing wording at https://github.com/getdnsapi/stubby/blob/develop/stubby.yml.example#L43. If your second case, all three values are valid. In the first one, I think only `TLS` should be, but that is not clear from the current documentation.

**Comment by saradickinson** [comment]
Sorry for the slow reponse - I'm out the office at RIPE this week.

I agree this is confusing and we have a long standing issue to change the API to make this more user friendly. This is mostly a hangover from when we evolving the API (which didn't include TLS or Strict/Opportunistic mode originally).

So the precendence is (IMHO) the wrong way round currently:

- The ```tls_authentication setting``` is ONLY honoured when TLS is the ONLY transport in the ```dns_transport_list```. It is silently ignored when this is not the case... we should at least detect and report this in the stubby log more effectively. 
- This means the transport list is the primary configuration, with ```tls_authentication setting``` a secondary setting. 

I'll leave this issue open and make sure to do a fix to the YAML file and the documentation to make this much clearer....

**Comment by monperrus** [comment]
is it an option to merge those two settings in a single one?

**Comment by saradickinson** [comment]
We are still figuring out the best way to change this part of the API. For example we are currently implementing DOH and it isn't yet clear how authentication will work for that (whether we can re-use the idea of Strict/Oppotunistic mode or not...). In some ways it is nice to separate the usage profile (which provides security properties regardless of transports) from the specific transports used but we also want an simple API....

**Comment by saradickinson** [comment]
I closing this issue as I don't expect a change to the API in the near future and the documentation has been updated since this was opened to try to explain this a bit better - so this will serve as a reference issue now.
