### ISSUE TITLE
stubby error on mac

### ISSUE THREAD

**Issue by ookangzheng** [getdnsapi/stubby#119]
Mac OSx High Sierra
I got an error while starting stubby
I install from brew
Error message:
dyld: Library not loaded: /usr/local/opt/libevent/lib/libevent-2.1.6.dylib
  Referenced from: /usr/local/opt/unbound/lib/libunbound.2.dylib
  Reason: image not found

**Comment by MindTooth** [comment]
Care to do a `brew doctor` & `brew --config`, post the output here.

Also, do a `brew update-reset`, `brew update` and `brew reinstall stubby`.

**Comment by ookangzheng** [comment]
brew --config
```
HOMEBREW_VERSION: 1.6.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: c814199a791867ab75f90a22715e2475706b13d8
Last commit: 13 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b314a662626e0a7fd61fb8f2a5e12fbbb04651e6
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.14.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_151
macOS: 10.13.5-x86_64
CLT: 10.0.0.0.1.1527767617
Xcode: N/A
XQuartz: N/A
```
After reinstall and reset brew, every works fine !

**Comment by saradickinson** [comment]
@MindTooth thanks for helping out, @ookangzheng glad everything works now. I'll close the issue - please re-open if you run into any more trouble.

**Comment by ookangzheng** [comment]
After next day, I restarted my mac I get an error 
<img width="818" alt="screen shot 2018-07-04 at 00 04 56" src="https://user-images.githubusercontent.com/6301735/42231359-efbed23e-7f1d-11e8-8167-f1827b6bf6d9.png">
But I switch to 
```
tls_authentication: GETDNS_AUTHENTICATION_NONE
``` 
No error, why ?

**Comment by saradickinson** [comment]
You can get more detailed errors if you run with full logging (add the -l flag t the command line). 
Perhaps switch back to GETDNS_AUTHENTICATION_REQUIRED and see what it says?
