### ISSUE TITLE
Level 4 log for when a resolver reaches tls_backoff_time

### ISSUE THREAD

**Issue by KonomiKitten** [getdnsapi/stubby#121]
Basically feature request that when a resolver reaches tls_backoff_time that stubby emit a log entry at level 4 (Warning). I'd like to be able to drop my current stubby logging level from v 5 to v 4 but currently as I see it there's no way to tell when a resolver is hitting the back off time at level 4 and level 5 is quite "chatty". Thank you.

**Comment by wtoorop** [comment]
Okidoki... it's in getds-1.5.0/stubby-0.2.4

**Comment by KonomiKitten** [comment]
> Okidoki... it's in getds-1.5.0/stubby-0.2.4

Thanks muchly!
