### ISSUE TITLE
DOES STUBBY WORK - NO PRIVACY?

### ISSUE THREAD

**Issue by lufoji** [getdnsapi/stubby#123]
If I understand correctly stubby encrypts DNS queries so no body can snoop on them locally or at ISP level.

I have installed stubby and it seems to be working I can see DNS queries are sent over port 853 but when I access a domain restricted by my ISP I can see that it is still blocked.

If I use another ISP I can see that the page is NOT blocked which means that my ISP is able to somehow detect my original DNS request. 

I wonder how this is possible are they able to break the TLS encryption?

**Comment by ArchangeGabriel** [comment]
A lot of things are possible here.

First, are you positive you that your browser is using Stubby for DNS requests? From what you say I believe so, but prefer to check. ;)

Second, are you sure your ISP is doing blocking based on DNS? They could do IP blocking, or they could do DPI and look at TLS SNI headers to see which website you’re trying to access.

Nowadays, DNS privacy is almost rendered useless by TLS SNI unfortunately…

**Comment by lufoji** [comment]
Browser is definitely using Stubby and I have checked the DNS results again and they appear to be correct and not modified. 

I believe you are correct that the ISP is using DPI and possibly TLS SNI to block the site which just means Stubby is only good for DNS verification and not privacy yet.

**Comment by saradickinson** [comment]
@lufoji @ArchangeGabriel A draft proposing encryption of TLS SNI has just been adopted by the TLS WG at IETF and so hopefully that will be addressed in the future too.

**Comment by ArchangeGabriel** [comment]
I know this was being worked on, but glad to see it’s actually coming. :)

**Comment by Frederick888** [comment]
Sorry to make a noise out of the blue. May I know whether Stubby currently support ESNI?

**Comment by saradickinson** [comment]
Not yet because there is no support in OpenSSL for ESNI. But I believe people are working on implementing that. Note also that the specification is still at the draft stage, not yet an RFC:https://datatracker.ietf.org/doc/draft-ietf-tls-esni/

Hopefully the draft will get an 'Implementation Status' section soon!
