### ISSUE TITLE
Getdns modification does not get reflected

### ISSUE THREAD

**Issue by shijimiYN** [getdnsapi/stubby#125]
When I modified a line of code in getdns (e.g. the [log](https://github.com/getdnsapi/getdns/blob/9b4e8e9e91618e8735c58d05b12f52cec2c760db/src/stub.c#L2242) that gets printed when I run Stubby using the `-l` argument from the command line), the modification does not show even if I re-build both Stubby and getdns.
Here are the list of things I have done to compile and build the code after I modified the getdns code:
```bash
$ cd getdns/build
$ make distclean
$ make
$ sudo make install
$ sudo stubby -l
```
Has anyone encountered the same situation? Any suggestions to resolve this issue? Thanks!

**Comment by saradickinson** [comment]
Can you provide the configure line you used?
Let's also double check which libgetdns your stubby is linking to:
For OS X use  
```
otool -L `which stubby`
```
For linux use
```
ldd  `which stubby`
```
Once you know this double check the timestamps on the library to see if it getting rebuilt.

**Comment by shijimiYN** [comment]
Thanks for the reply!

Here's the configure line used for configuring getdns:
`../configure --enable-stub-only --with-stubby --without-libidn --without-libidn2`

I've checked which libgetdns my stubby is linking to, and I've confirmed that that libgetdns is getting rebuilt.

**Comment by saradickinson** [comment]
In that case I suspect something else is going here... Do you want to send me a diff of your changes so I can double check that you should see a change in the stubby output? If you want to do this offline feel free to send to sara@sinodun.com

**Comment by shijimiYN** [comment]
All of the sudden, the changes in getdns started to get reflected to stubby...!
I'm still trying to look into why the changes didn't get reflected initially, but until then, I think this is case closed :)
Thanks, @saradickinson for helping me out!
