### ISSUE TITLE
TLS 1.3 / openssl 1.1.1

### ISSUE THREAD

**Issue by obendev** [getdnsapi/stubby#130]
Since TLSv1.3 has a [RFC doc](https://tools.ietf.org/html/rfc8446) now and openssl released version 1.1.1 with TLS 1.3 support, will Stubby also get TLS 1.3 / the new openssl Version?

https://github.com/openssl/openssl/releases/tag/OpenSSL_1_1_1
https://wiki.openssl.org/index.php/TLS1.3

Edit:
Windows installer was just updated: https://github.com/getdnsapi/stubby/issues/132#issuecomment-435946613

Now there only needs to be a "TLS 1.3 only"-function or something like that.

**Comment by obendev** [comment]
I do not understand it entirely, how does stubby TLS 1.3?
I thought it has only openssl version 1.1.0g, does TLS 1.3 already work there?

**Comment by ArchangeGabriel** [comment]
Well it depends how you get Stubby. On most Linux distros, it should just use the system OpenSSL, so if yours was upgraded to 1.1.1, it should just work. I don’t know a way to check it correctly uses TLS 1.3 on my system, but it should.

**Comment by obendev** [comment]
Okay I'm using it on Windows so I have to wait until stubby gets updated

**Comment by saradickinson** [comment]
@obendev Yes - we need to update the Windows and macOS UI Stubby packages to use a more recent version of OpenSSL to provide TLS 1.3 - it's on the TODO list!
(You can build Stubby from source on Windows and link against any version of OpenSSL you like but it you need to know what you are doing :-) ).

**Comment by obendev** [comment]
Okay, thank you very much for the information. 😃 
Maybe add the enhancement label?

**Comment by obendev** [comment]
https://github.com/getdnsapi/stubby/issues/132#issuecomment-422783293

**Comment by obendev** [comment]
Update: Just found out that 1.1.1 is LTS: https://www.openssl.org/blog/blog/2018/09/11/release111/

> Since 1.1.1 is our new LTS release we are strongly advising all users to upgrade as soon as possible.

**Comment by obendev** [comment]
@saradickinson is there any way on windows to use the openssl 1.1.1 version?
Or can I build the windows installer with openssl 1.1.1 myself?

**Comment by obendev** [comment]
Windows installer was just updated: https://github.com/getdnsapi/stubby/issues/132#issuecomment-435946613

Now there only needs to be a "TLS 1.3 only"-function or something like that.

**Comment by ArchangeGabriel** [comment]
@obendev You mean something like `tls_version_list: "TLSv1.3:TLSv1.2"`? That would be nice indeed. Maybe you can make a FR on getdns?

**Comment by obendev** [comment]
Yes!
btw, do you know if Cloudflare supports DNS over TLS also on the IPv6?

**Comment by wtoorop** [comment]
New getdns 1.5.0 has limiting to specific TLS version. See: 
https://getdnsapi.net/releases/getdns-1-5-0/ and https://getdnsapi.net/functions/getdns_context_set_tls_min_version.html

**Comment by laggardkernel** [comment]
I just added a macOS stubby with TLS 1.3 (openssl 1.1) support in my own homebrew tap.

```bash
brew install laggardkernel/tap/stubby
```

Then enable TLS v1.3 with `tls_min_version: GETDNS_TLS1_3` in your config.
