### ISSUE TITLE
Error while build stubby over source (linux)

### ISSUE THREAD

**Issue by jamesbond55** [getdnsapi/stubby#137]
Hi,

know mayby this the wrong place but i don't know where i can ask to solve my problem.
So i tried to build it from over source on my rasperrs pie. Until the 'make' everthing works but when i try to execute the 'make' command i get this error:

make [1]: No rule available to create the target /src/jsmn/jsmn.h (necessary for 'convert.lo'). 
Makefile:53: The rule for target 'default' failed
And then i get the error 2.

I don't have any idea why this happened by me but any help would be nice. I used this guide:
https://stafwag.github.io/blog/blog/2018/09/09/dns-privacy-with-stubby-part1-gnulinux/

**Comment by jamesbond55** [comment]
hi sara,

in my opinion i done that. 
That are my command which typed so far:

1. sudo apt-install build-essential git libtool autoconfig libssl-dev libyaml-dev
The following question with the questions i answered with yes 
2. cd /home/pi/getdns
3. git tag
4. git checkout v1.4.2
5. git submodule update --git 
7. libtoolize -ci
8. autoconf -fi
9. mkdir build
10. cd build/
11. ../configure --prefix=/usr/local --without-libidn --withoutlibidn2 --enable-stub-only --with stubby

Mayby the dependencies in the first command aren't completly correct? When you need it i can give you what the the pie wrote in the terminal while he execute the commands. 

And thx for fast response.

**Comment by saradickinson** [comment]
Is it a typo in item 6?
```git submodule update --git``` should be
```git submodule update --init```

**Comment by jamesbond55** [comment]
h sara thx for the answer. I test it and yes i'm made progress. The installation was successfull and activation of stubby works now. Now i'm at the testing part.

But at this point i have a little problem/question. I installed the dnsutils package to run this command:
dig @127.0.0.1 -p 53000 www.startpage.com

But when i excute this command i get a connection timeout. But the pi says that 1 server is found. The stubby service is enabled. I checked it with the systmctl command.
So i'm not sure why i get the timeout. Any ideas?

**Comment by jamesbond55** [comment]
Update:

ok i test it with the command on your page (dig @127.0.0.1 www.startpage.com) instead of the mentioned command above. And then i get  a answer from the 127.0.0.1 (as it should be).


Then i edit the resolvconfig file in the etc folder and check the dns with the site 'www.dnsleaktest.com'.  Now i see your dns server (yeah). But in the stubby logging i get the notification 'Backing off TLS on this connection - Will retry again' in in seconds intervall and by current and best auth often stands 'None'.
Afterthe retry it switch to success in the mentioned fields but only for short amount of time. 
The mentioned behavior comes again.

**Comment by saradickinson** [comment]
Reviewing old issues and closing this one because of the age. Note that Stubby 0.3.0 moved to the cmake build system.
