### ISSUE TITLE
Feature request: "cloaking rules"

### ISSUE THREAD

**Issue by jackyaz** [getdnsapi/stubby#138]
Similar to dnscrypt, allow specification of a hosts file when wanting to retain local name resolution when using Stubby as the main DNS resolver for a set of devices

**Comment by saradickinson** [comment]
I think we have already had this request and this is also on the roadmap: https://github.com/getdnsapi/stubby/issues/32

**Comment by saradickinson** [comment]
I'm reviewing issues and will close this now as it is effectively an duplicate of  #32 which is still on the enhancement list
