### ISSUE TITLE
dot server switzerland

### ISSUE THREAD

**Issue by ibksturm** [getdnsapi/stubby#142]
hi all

i‘m running on https://ibksturm.synology.me a dns server, protokolls supporter

doh (listet on the dnscrypt public gitrepo)
dnscrypt (see topline)
dot (newly reconfiguret)

please ad my server(s) to your testresolcerlist

- nologging
- no filters
- dnssec
- opennic root copy
- iana root copy
- nginx load balancer, unbound backend

Code is on Github [https://github.com/ibksturm/dnscrypt-switzerland](https://github.com/ibksturm/dnscrypt-switzerland) 

doh and dnscrypt should running stable, dot i need some external testers

@saradickinson 
Could you please put it on [https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Test+Servers](https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Test+Servers) or in case of not, tell me please the reason why, that i can make it better :) 

have fun

**Comment by saradickinson** [comment]
Two problems I have found:
1) Right now I can't get an answer from 178.82.103.5 using DoT
2) Also, if I dig for the A record of ibksturm.synology.me I get a different IP (217.162.206.220) than the one above (which you listed in stubby.yaml.example). This IP address doesn't offer DoT either. This will cause problems for some client software so our recommendation is to run the DoT service endpoint at the A record for the authentication domain name.

**Comment by ibksturm** [comment]
hi @saradickinson 

thanks a lot for your response :)

1. ISP changed the address in Februar to 217.162.206.220.... the marketing and public relations people are more paied than the techguys who have to managed the things.... 

2. ok i will show the stubby.yaml.example, sorry i've i forget to do correct the entry... it's hard getting older ;)

**Comment by saradickinson** [comment]
Added

**Comment by ibksturm** [comment]
thanks a lot @saradickinson :)

i will open a beer to celebrate adding my server and cheers to you
