### ISSUE TITLE
Stubby configuration sharing

### ISSUE THREAD

**Issue by bellocarico** [getdnsapi/stubby#144]
First of all about Stubby: wow! 👍

I have a little request you might want to consider. Given the number of providers are somehow limited nowadays, I wanted to suggest if on this page:

https://dnsprivacy.org/jenkins/job/dnsprivacy-monitoring/

you would consider adding two columns to that table. 
- One for sharing the Stubby configuration needed to use that server
- The second with a link for the DNS verification on a provider basis like Cloudflare does here: https://1.1.1.1/help

Thanks

**Comment by saradickinson** [comment]
Closing this issue as I hope the above information resolves it.
