### ISSUE TITLE
 *FAILURE* no valid transports or upstreams available!

### ISSUE THREAD

**Issue by Warok21** [getdnsapi/stubby#145]
Hi,
I've created my own DNS server, and I used let's encrypt to generate the certificates.

### Client :
Windows 10
Content of stubby.yml:

```
resolution_type: GETDNS_RESOLUTION_STUB
dns_transport_list:
GETDNS_TRANSPORT_TLS
tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
tls_query_padding_blocksize: 128
edns_client_subnet_private : 1
round_robin_upstreams: 1
idle_timeout: 10000
listen_addresses:
127.0.0.1
0::1
upstream_recursive_servers:
address_data: 160.98.31.165
tls_auth_name: "cn that I used in the command"
tls_pubkey_pinset:
digest: "sha256"
value: computed hash
```

### Expected behaviour
Client making the connection with the server

### Actual behaviour

> FAILURE no valid transports or upstreams available!
> Could not schedule query: None of the configured upstreams could be used to send queries on the specified transports

Can anyone help me please?
I don't know what I'm doing wrong

**Comment by Warok21** [comment]
Here is a better copy paste from my config file https://pastebin.com/2PfRS5QP.
And yes, I have ACL, if I go to my server and check with the command 
`openssl s_client -connect 160.98.31.165:853`
The return code is ok (more detail https://pastebin.com/mPteGGMA)
To generate the base64 I used the following command 
`echo -n fullchain.pem |openssl dgst -binary -sha256 | openssl base64 `

**Comment by ArchangeGabriel** [comment]
OK, then I can’t see anything wrong, you will have to wait for @saradickinson or @wtoorop to come with debugging command in order to understand what is going wrong.

**Comment by Warok21** [comment]
Oky, thanks, wait for it

**Comment by wtoorop** [comment]
Could you please run:
```
getdns_query.exe  -sLmy 7 @160.98.31.165~xxx -K 'pin-sha256=xxxh""'
```
And copy paste the output of that?
Thanks!

**Comment by Warok21** [comment]
Here is the output :https://pastebin.com/13FhWQaE

**Comment by wtoorop** [comment]
Oh sorry... I made a mistake (with quotes in the `-K` option), could you instead run:
```
getdns_query.exe  -sLmy 7 @160.98.31.165~xxx -K 'pin-sha256="xxx="'
```

**Comment by Warok21** [comment]
> C:\Program Files\Stubby>getdns_query.exe -sLmy 7 @160.98.31.165~adriano.tic.heia-fr.ch -K 'pin-sha256="ibH80gkCL8vVHyjtWNplkJdue9guBYjRtkdKiekxprY="'
> could not convert ''pin-sha256=ibH80gkCL8vVHyjtWNplkJdue9guBYjRtkdKiekxprY='' into a public key pin.
> Good pins look like: pin-sha256="E9CZ9INDbd+2eRQozYqqbQ2yXLVKB9+xcprMF+44U1g="
> Please see RFC 7469 for details about the format

**Comment by Warok21** [comment]
> > C:\Program Files\Stubby>getdns_query.exe -sLmy 7 @160.98.31.165~adriano.tic.heia-fr.ch -K 'pin-sha256="ibH80gkCL8vVHyjtWNplkJdue9guBYjRtkdKiekxprY="'
> > could not convert ''pin-sha256=ibH80gkCL8vVHyjtWNplkJdue9guBYjRtkdKiekxprY='' into a public key pin.
> > Good pins look like: pin-sha256="E9CZ9INDbd+2eRQozYqqbQ2yXLVKB9+xcprMF+44U1g="
> > Please see RFC 7469 for details about the format

**Comment by wtoorop** [comment]
Ah again something wrong with the quotes (but now specific to `command.com`). I managed with these quotes and backslashes:
```
getdns_query.exe  -sLmy 7 @160.98.31.165~xxx -K "pin-sha256=\"xxx=\""
```

**Comment by Warok21** [comment]
> C:\Program Files\Stubby>getdns_query.exe -sLmy 7 @160.98.31.165~adriano.tic.heia-fr.ch -K "pin-sha256=\"ibH80gkCL8vVHyjtWNplkJdue9guBYjRtkdKiekxprY=\""
> [14:13:06.506640] UPSTREAM 160.98.31.165                            : Conn opened: TLS - Strict Profile
> [14:13:06.509639] UPSTREAM 160.98.31.165                            : Verify failed : TLS - *Failure* -  Pinset validation failure
> [14:13:06.509639] UPSTREAM 160.98.31.165                            : Conn closed: TLS - *Failure*
> [14:13:06.509639] UPSTREAM    *FAILURE* no valid transports or upstreams available!
> [14:13:06.509639] UPSTREAM 160.98.31.165                            : Conn closed: TLS - Resps=     0, Timeouts  =     0, Curr_auth = Failed, Keepalive(ms)=     0
> [14:13:06.509639] UPSTREAM 160.98.31.165                            : Upstream   : TLS - Resps=     0, Timeouts  =     0, Best_auth = Failed
> [14:13:06.509639] UPSTREAM 160.98.31.165                            : Upstream   : TLS - Conns=     0, Conn_fails=     1, Conn_shuts=      0, Backoffs     =     0
> [14:13:06.509639] UPSTREAM 160.98.31.165                            : Conn closed: TLS - Resps=     0, Timeouts  =     0, Curr_auth =   None, Keepalive(ms)=     0
> [14:13:06.510627] UPSTREAM 160.98.31.165                            : Upstream   : TLS - Resps=     0, Timeouts  =     0, Best_auth = Failed
> [14:13:06.510627] UPSTREAM 160.98.31.165                            : Upstream   : TLS - Conns=     0, Conn_fails=     2, Conn_shuts=      0, Backoffs     =     0
> [14:13:06.510627] UPSTREAM 160.98.31.165                            : Upstream   : !Backing off TLS on this upstream    - Will retry again in 2s at Wed Jan 02 14:13:08 2019
> An error occurred: 1 'Generic error'

**Comment by wtoorop** [comment]
Thanks!

So I now see the pin is not extracted from the certificate correctly.  The pin should be made over the public key of the certificate (and not over the word 'fullchain.pem' ;). To extract it from the `cert.pem` file, do:
```
openssl x509 -in cert.pem -pubkey -noout | openssl pkey -pubin -outform der | openssl dgst -sha256 -binary | openssl base64
```
Alternatively to extract it from the over TLS presented certificate, do:
```
echo -n | openssl s_client -connect 160.98.31.165:853 -showcerts | openssl x509 -pubkey -noout | openssl pkey -pubin -outform der | openssl dgst -sha256 -binary | openssl base64

```

**Comment by Warok21** [comment]
It works!!!
Thanks a lot!!!!!!!!!

**Comment by wtoorop** [comment]
Very welcome :) Happy new year!

**Comment by Warok21** [comment]
You too :)
