### ISSUE TITLE
Feature Request: fallback resolver.

### ISSUE THREAD

**Issue by odkrys** [getdnsapi/stubby#146]
Normally embedded devices don't have battery to save system time.
For this reason, the devices fail to get auth of tls resolver so they fail to resolve ntp server name when start or restart with stubby.
We can configure ntp server name go through specific server like "server=/pool.ntp.org/1.1.1.1" but it would be better if stubby support solution itself.

Another dns encryption package dnscrypt-proxy2 has fallback_resolver option.
Can this feature implement in stubby ?
```
## Fallback resolver
## This is a normal, non-encrypted DNS resolver, that will be only used
## for one-shot queries when retrieving the initial resolvers list, and
## only if the system DNS configuration doesn't work.
## No user application queries will ever be leaked through this resolver,
## and it will not be used after IP addresses of resolvers URLs have been found.
## It will never be used if lists have already been cached, and if stamps
## don't include host names without IP addresses.
## It will not be used if the configured system DNS works.
## A resolver supporting DNSSEC is recommended. This may become mandatory.
##
## People in China may need to use 114.114.114.114:53 here.
## Other popular options include 8.8.8.8 and 1.1.1.1.

fallback_resolver = '9.9.9.9:53'
```

**Comment by odkrys** [comment]
It looks dnscrypt-proxy2 accept 9 months difference while stubby only accept 2 months difference of system time.
fallback_resolver of dnscrypt-proxy2 is not designed to resolve the problem described above.

I still hope to find something solution what handle this problem as well.
Right now, manual configuration, or fake-hwclock would be helped.

**Comment by tomdov** [comment]
Hello,
from your query it seems like the Opportunistic profile is what's needed for this case:
if the authentication isn't succeeding, it will fail back to clear - then allow the ntp to be resolved, ntp will sync the system. Have you tried it?
