### ISSUE TITLE
Document missing config options

### ISSUE THREAD

**Issue by jonathanunderwood** [getdnsapi/stubby#148]
It looks like, with version 0.2.4 (and getdns 1.5.0) the following config options are now exposed:

* `tls_ciphersuites` (for TLS >= 1.3)
* `tls_cipher_list` (for TLS < 1.3)
* `tls_min_version`
* `tls_max_version`

That being the case, they should be documented in the example config file.

**Comment by wtoorop** [comment]
Acknowledged.  Tentatively scheduled for next Monday.

**Comment by saradickinson** [comment]
Closing as fixed
