### ISSUE TITLE
Google Public DNS

### ISSUE THREAD

**Issue by ArchangeGabriel** [getdnsapi/stubby#149]
Now support DNS-over-TLS: https://developers.google.com/speed/public-dns/docs/dns-over-tls

Should be added to https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Public+Resolvers I guess.

**Comment by wtoorop** [comment]
Thanks Bruno, I'm not completely sure about how public this is, as it is not announce here yet: https://groups.google.com/forum/#!forum/public-dns-announce .

**Comment by ArchangeGabriel** [comment]
I see you’ve found the announcement, sorry for not linking it in the first place. Note that there is also DoH (https://developers.google.com/speed/public-dns/docs/dns-over-https), but experimental.

**Comment by saradickinson** [comment]
There are links to other sites that keep closer track of DoH servers - a good place to start is this page:
https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Public+Resolvers#DNSPrivacyPublicResolvers-DNS-over-HTTPS(DoH)

Support for Google DoT added in 0.2.4 release
