### ISSUE TITLE
Missing dnssec_return_status: GETDNS_EXTENSION_TRUE

### ISSUE THREAD

**Issue by hanvinke** [getdnsapi/stubby#151]
In the new 1.5.1 version there is in the stubby.yml file and the example a small error:
There should be: "dnssec_return_status: GETDNS_EXTENSION_TRUE"

But it says "dnssec: GETDNS_EXTENSION_TRUE". 

I cannot get DNSSEC to work, even with "dnssec_return_status: GETDNS_EXTENSION_TRUE" enabled. Has something changed in enabling DNSSEC?

//edit: I am still investigating why DNSSEC does not work for me.

**Comment by hanvinke** [comment]
Solved it. I had to mark again "# dnssec_return_status: GETDNS_EXTENSION_TRUE".
Strange, I thought this option had to be unmarked for DNSSEC validation?

Yet I still don't know why this option has changed in the stubby.yml file to "dnssec: GETDNS_EXTENSION_TRUE". Intentionally?

**Comment by saradickinson** [comment]
Have a look at the 1.5.0 release notes - this option is now the default as it will hard fail if the trust anchor can't be fetched (the previous option failed silently):
https://getdnsapi.net/releases/getdns-1-5-0-rc1/

**Comment by hanvinke** [comment]
Thank you for the response. I found the info about: 
"A new extension names just dnssec, which requires that DNSSEC verification is performed." 
Does this imply that "dnssec_return_status" is obsolete now?

And sorry for the confusion about DNSSEC not working in my browser. I forgot that I was testing the new DNS over HTTPS with eSNI possibilities in Firefox. I was still using the internal Cloudflare resolver instead of Stubby...

**Comment by saradickinson** [comment]
No, `dnssec_return_status` is not obsolete, it is still available (and retains its original behaviour) - 
what you see in the stubby.conf.example file is just the subset of all the possible options in the getdns API that are directly relevant for and form the default configuration for stubby.
