### ISSUE TITLE
Unclear documentation for Zero Configuarion DNSSEC in Windows

### ISSUE THREAD

**Issue by Big--Mike** [getdnsapi/stubby#153]
Hi, 
the documentation states, that the keys fetched and stored in your *home directory* in a subfolder *.getdns*.

That would correspond to **%userprofile%\\.getdns**
In fact, **%appdata%\\getdns** (the missing . is no typo) is used by default.

**Comment by banburybill** [comment]
Documentation fixed in develop.

**Comment by Big--Mike** [comment]
Thank you :)
