### ISSUE TITLE
Problems with Windows binaries (Stubby 0.0.6)

### ISSUE THREAD

**Issue by Big--Mike** [getdnsapi/stubby#154]
- There seems to be no x86 version of binaries, only x64, would it be possible to provide also a x86 version of the binaries
- If I try to run getdns_server_mon.exe (SHA-1 F0F53980E31E6D95930C36CBABD99EAEFF37EC39) in WIndows 10 x64, where stubby binary is working, I also get the error, that getdns_server_mon.exe is not suited for my platform

I downloaded the zip package.

**Comment by Big--Mike** [comment]
getdns_server_mon.exe is working fine on Windows 10 x64 now.
Using Stubby 0.0.7 package

**Comment by banburybill** [comment]
New release 0.2.5.0 of the Windows binaries/installer now includes a x86 version.

**Comment by Big--Mike** [comment]
Very cool :) Thank you
