### ISSUE TITLE
DNSSEC validation: Strange behavior

### ISSUE THREAD

**Issue by Big--Mike** [getdnsapi/stubby#155]
Hi,
it seems, that if the trust chain can't be validated, strict DNSSEC validation is simply ignored. Is this intended?
I've tested by cleaning the DNSSEC keys, stored on my disk and blocking port 80 for stubby (so that keys can't be fetched). I try to resolve sigfail.verteiltesysteme.net, which is a test domain with broken DNSSEC.

Stubby output is:
_.\stubby.exe -l -C .\stubby.yml
[16:11:51.917586] STUBBY: Read config from file .\stubby.yml
[16:11:51.923567] STUBBY: DNSSEC Validation is ON
[16:11:51.924565] STUBBY: Transport list is:
[16:11:51.925571] STUBBY:   - TLS
[16:11:51.926572] STUBBY: Privacy Usage Profile is Strict (Authentication required)
[16:11:51.927568] STUBBY: (NOTE a Strict Profile only applies when TLS is the ONLY transport!!) [16:11:51.928554] STUBBY: Starting DAEMON....
[16:11:59.527626] STUBBY: 145.100.185.15                           : Conn opened: TLS - Strict Profile
[16:11:59.650284] STUBBY: 145.100.185.15                           : Verify passed : TLS[16:11:51.917586]_ 

With blocked port 80, I get with (Windows) nslookup:
_nslookup sigfail.verteiltesysteme.net 127.0.0.1
DNS request timed out.
    timeout was 2 seconds.
Server:  UnKnown
Address:  127.0.0.1_

_DNS request timed out.
    timeout was 2 seconds.
Name:    sigfail.verteiltesysteme.net
Address:  2001:638:501:8efc::139_

When I allow port 80 (such that the certificate chain could be validated):
_nslookup sigfail.verteiltesysteme.net 127.0.0.1
DNS request timed out.
    timeout was 2 seconds.
Server:  UnKnown
Address:  127.0.0.1_

_DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** sigfail.verteiltesysteme.net wurde von UnKnown nicht gefunden: Server failed._

I would expect to get a SERVFAIL in any case. The resolver should identify, that DNSSEC is broken for this domain, even if the chain can't be validated. And I would expect some messages in the stubby log about the validation problems.

**Comment by wtoorop** [comment]
With the old `dnssec_return_status` extension this was the case yes. You need to use the new `dnssec` extension introduced in stubby version 0.2.4 with getdns-1.5.0.

**Comment by Big--Mike** [comment]
Ok, then I'll have to wait until Windows binaries for version 0.2.4 are available.
At the moment, the installation package contains version 0.2.3...

Thank you for the quick response :)
