### ISSUE TITLE
Stubby-Installer-Asuswrt-Merlin 

### ISSUE THREAD

**Issue by Xentrk** [getdnsapi/stubby#159]
Please consider adding the https://github.com/Xentrk/Stubby-Installer-Asuswrt-Merlin to the current work efforts on the https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+-+Current+Work page.

The effort is actively being maintained and improved and the number of users has grown since the project was launched in October 2018.  

References:

GitHub Repo: https://github.com/Xentrk/Stubby-Installer-Asuswrt-Merlin
Support Forum: https://www.snbforums.com/threads/stubby-installer-asuswrt-merlin.49469/
For information on how the settings were derived at, see my blog post at: https://x3mtek.com/dns-over-tls-with-dnsmasq-and-stubby-on-asuswrt-merlin/

**Comment by saradickinson** [comment]
We did already have some mention of this in the Current work (see Aug 2018) and on the clients page, but I've added the extra links on the client page: 
https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Clients#DNSPrivacyClients-Routers
And a new entry in the Jan 2018 Current work to link to this. 

Thanks for all your work on this!
