### ISSUE TITLE
Lots of backing off with Google DNS servers

### ISSUE THREAD

**Issue by timkgh** [getdnsapi/stubby#162]
Stubby v0.2.2 on Ubuntu 18.04

Seeing lots of these in the log with the Google DNS servers, both 8.8.8.8 and 8.8.4.4:

`[11:45:00.622811] STUBBY: 8.8.4.4 : Upstream   : !Backing off TLS on this upstream    - Will retry again in 2s at Thu Jan 24 11:45:02 2019`

I also have Cloudflare and Quad9 configured and they are quiet.

Is it normal to see these log messages or a sign of a problem? DNS sometimes hangs and can't resolve some names.

**Comment by saradickinson** [comment]
Hi there, I did some local testing and did see some some issues with Google intermittently not responding, bu I didn't see stubby backoff as you did. I would not expect to see this log message - it does indicate that there is a problem with Google. Note that Google is an anycast service so it is possible it is an issue local to you (e.g with their servers in your region or with something blocking your access). 

I can't immediately figure out why I'm seeing problems - I will try to investigate....

**Comment by timkgh** [comment]
It looks more stable now, the message showed up only once in the past 24 hrs. Google DoT is still new, it's possible they are still working on making it more reliable.

**Comment by timkgh** [comment]
Ubuntu 18.04 repos have an older Stubby v0.2.2 Any good reason to try and run the latest stubby release? Just want to make sure the back offs I'm seeing are not a stubby issue but a server problem instead.

**Comment by saradickinson** [comment]
Nope - nothing has changed with that behaviour since then that I know of, I don't think it is a stubby issue.  Glad it is more stable, and as you say Google DoT is still quite young!

**Comment by saradickinson** [comment]
I'm closing as this hasn't been updated since January - please re-open if you have further problems
