### ISSUE TITLE
stubby in docker

### ISSUE THREAD

**Issue by loskiq** [getdnsapi/stubby#165]
My stubby are used in a docker container. How to set listen address in stubby.yml to 0.0.0.0?

**Comment by saradickinson** [comment]
Update the following configuration option in the stubby.conf file:

```listen_addresses:
  - 127.0.0.1
  -  0::1```

**Comment by loskiq** [comment]
@saradickinson don't work. stubby still listening 127.0.0.1

**Comment by kometchtech** [comment]
@loskiq 

I am running stubby in the docker environment, but I am listening at `0.0.0.0`.
```
listen_addresses:
  -  0::1
  - 0.0.0.0
```
```
# netstat -anup
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
udp        0      0 0.0.0.0:53              0.0.0.0:*                           1/stubby
udp        0      0 127.0.0.11:41162        0.0.0.0:*                           -
udp        0      0 ::1:53                  :::*                                1/stubby
```

**Comment by loskiq** [comment]
sorry. the problem was in the wrong way to config. thanks!

**Comment by pataquets** [comment]
@loskiq : you might be interested in PR #310, since it might be useful to you in the future.
