### ISSUE TITLE
Stubby still resolving even when CA can’t be verified

### ISSUE THREAD

**Issue by eccgecko** [getdnsapi/stubby#166]
So in my stubby.yml config, I have included the option `tls_ca_file: “user/share/ca-certificates/trust-source/mozilla.trust.p11-kit”` for CA certificate verification in stubby.

This works fine. When the daemon starts up, it reports `STUBBY: --- SETUP(TLS): : Verify locations loaded`

All ok. However, as a test, I decided to edit the name of the location to a non-existent file. To my surprise, the daemon loads normally and can resolve anyway. There is this line in the daemon log as it starts `STUBBY: --- SETUP(TLS): : Could not load verify locations (error:02001002:system library:fopen:No such file or directory)`

However, it then goes on to resolve just fine:
`STUBBY: 1.1.1.1                                  : Conn opened: TLS - Strict Profile`
`STUBBY: 1.1.1.1                                  : Verify passed : TLS`

So my question is whether or not this is a feature or a bug? Should the option to verify the CA certs of the server you connect to not mean that resolve should fail when stubby can’t verify them?

**Comment by wtoorop** [comment]
Unless you have a pinset defined, a non-existing verify location should have failed. It does with me:
```
getdns_query '{tls_ca_path:"qwer"}' -sL @1.1.1.1~cloudflare-dns.com -n nlnet.nl A +return_call_reporting -y 7 -m
[14:04:10.360774] UPSTREAM --- SETUP(TLS): : Verify locations loaded
[14:04:10.360996] UPSTREAM 1.1.1.1                                  : Conn opened: TLS - Strict Profile
[14:04:10.371125] UPSTREAM 1.1.1.1                                  : Verify failed : TLS - *Failure* - (20) "unable to get local issuer certificate"
[14:04:10.371155] UPSTREAM 1.1.1.1                                  : Conn closed: TLS - *Failure*

```

**Comment by saradickinson** [comment]
@wtoorop - looking at the code it seems it falls back to trying to load the default certs, so the behaviour will depend on whether they exist?

**Comment by eccgecko** [comment]
> @wtoorop - looking at the code it seems it falls back to trying to load the default certs, so the behaviour will depend on whether they exist?

@saradickinson Ah, this makes sense, assuming that by default certs location you mean the one listed in the example stubby.yml config (/etc/ssl/certs/)? Because they do indeed also exist in there, although I prefer to use the mozilla ones.

**Comment by saradickinson** [comment]
I'm going to close this issue as I think it is resolved.
