### ISSUE TITLE
RST from Cloudflare

### ISSUE THREAD

**Issue by CarlTuckerson** [getdnsapi/stubby#183]
Running Stubby on Windows 10, Wireshark show constant RST from the Cloudflare servers. I changed "idle_timeout: 10000" to 9000 and it stopped. 
Also earlier I changed the "timeout:" from the commented out default to 7500 when the Stubby logging showed a consistent timeout from one of the Cloudflare addresses. Haven't seen that since the change.

**Comment by CarlTuckerson** [comment]
Update: adding timeout: 7500 unnecessary, no longer specifying any timeout, the secondary IPv6 Cloudflare server must have been slow that day. Been working fine left at default, i.e., unspecified in the Stubby.yml.
I've been using a value of 9500 for idle_timeout and wireshark shows both Stubby client and Cloudflare servers exchanging FIN/ACK's. Setting it back to 10000 always results in Cloudflare servers closing connections with RST. Taking 0.5 second off the keepalives seems more graceful, but I could be wrong.

**Comment by saradickinson** [comment]
Thanks for this observation - I've added a comment to the stubby.yml file to use a shorter idle_timeout if using Cloudflare!
