### ISSUE TITLE
Misleading comment in /etc/systemd/system/stubby.service

### ISSUE THREAD

**Issue by tboerner** [getdnsapi/stubby#198]
stubby.service contains a comment giving direction whether to set DynamicUser=true or to set stubby as user explicitly. 
Expected: User=stubby
Found: DynamicUser=stubby
Result: stubby is silently run by root if this is set.

Found this in the German localized version, not sure whether other languages are affected, too.

**Comment by ArchangeGabriel** [comment]
Which distro? Can you show us the file? The [official one](https://github.com/getdnsapi/stubby/blob/develop/systemd/stubby.service) has nothing to be localized, and its content at those lines is:
```
User=stubby
DynamicUser=yes
```
which means Stubby is ran as `stubby`, which is created dynamically at runtime and discarded afterwards.

**Comment by tboerner** [comment]
My distro is Debian 9 (stretch) which doesn't contain Stubby yet. LANG=de_DE.UTF.8
I've installed Subby from the sources as follows:


git pull https://github.com/getdnsapi/getdns.git
git submodule update --init
libtoolize -ci
autoreconf -fi
mkdir build
cd build
../configure --prefix=/usr/local:
. --without-libidn --without-libidn2 --enable-stub-only --with-stubby
make

After install there is a file /etc/systemd/system/stubby.service:

-------- snip --------
Unit]
Description=DNS Privacy Stub Resolver
Documentation=https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Daemon+-+Stubby
Wants=network-online.target
After=network-online.target

# Konfigurationsvarianten fuer den Abschnitt [Service]:
# ----------1-----------------------------------
# Die ersten beiden Zeilen *nicht* auskommentieren, wenn
# Stubby verzoegert starten soll. Das ist nicht
# erforderlich, wenn Dnsmasq nur an zugewiesene
# Loopback-Interfaces bindet. Siehe /etc/dnsmasq.d/
# ----------2-----------------------------------
# Je nach Installation (/usr/bin oder /usr/local/bin)
# muss eine der beiden ExecStart-Zeilen
# auskommentiert werden
# ----------3-----------------------------------
# Falls Sie Stubby mit apt oder apg-get als Paket installiert
# haben, aktivieren Sie DynamicUser=true
# Falls Sie Stubby aus den Quellen installiert haben
# aktivieren Sie DynamicUser=stubby

[Service]
ExecStartPre=/bin/sleep 30
Type=idle
WorkingDirectory=/run/stubby
#ExecStart=/usr/bin/stubby
#ExecStart=/usr/local/bin/stubby
AmbientCapabilities=CAP_NET_BIND_SERVICE
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
RuntimeDirectory=stubby
#DynamicUser=true
#DynamicUser=stubby

[Install]
WantedBy=multi-user.target
-------- snap --------

The German comment gives directions which lines to uncomment according to the installing method. 
The statement "DynamicUser=stubby" appears twice. It should be "User=stubby".


Am 7. August 2019 18:53:13 MESZ schrieb Bruno Pagani <notifications@github.com>:
>Which distro? Can you show us the file? The [official
>one](https://github.com/getdnsapi/stubby/blob/develop/systemd/stubby.service)
>has nothing to be localized, and its content at those lines is:
>```
>User=stubby
>DynamicUser=yes
>```
>which means Stubby is ran as `stubby`, which is created dynamically at
>runtime and discarded afterwards.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/getdnsapi/stubby/issues/198#issuecomment-519180947

-- 
Thomas Börner 
Werderstr. 8 
35037 Marburg

Tel +49 (6421) 682104  
Fax +49 (6421) 682114  
mailto:thomas@boerner.click 
GPG: https://crypt.boerner.click (Fingerabdruck: 59EC 235C 949C AF4D 387D 40CF 29F7 2265 3197 8E56)

**Comment by ArchangeGabriel** [comment]
I have no idea where this systemd service file is coming from, but I definitively don’t see how it can be related to an installation from getdns repo…

Anyway, since you are on Debian Stretch, you only have systemd 232 and should not use DynamicUser for stubby (see discussion starting at https://github.com/getdnsapi/stubby/issues/106#issuecomment-390209681).

**Comment by tboerner** [comment]
I've no idea either, I thought it came from the repo.
Yes, I had to set User=stubby where I had found DynamicUser=stubby in the comment. Otherwise it ran with root privileges.

Am 9. August 2019 12:23:22 MESZ schrieb Bruno Pagani <notifications@github.com>:
>I have no idea where this systemd service file is coming from, but I
>definitively don’t see how it can be related to an installation from
>getdns repo…>
>>
>Anyway, since you are on Debian Stretch, you only have systemd 232 and
>should not use DynamicUser for stubby (see discussion starting at
>https://github.com/getdnsapi/stubby/issues/106#issuecomment-390209681).>
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/getdnsapi/stubby/issues/198#issuecomment-519867615

-- 
Thomas Börner 
Werderstr. 8 
35037 Marburg

Tel +49 (6421) 682104  
Fax +49 (6421) 682114  
mailto:thomas@boerner.click 
GPG: https://crypt.boerner.click (Fingerabdruck: 59EC 235C 949C AF4D 387D 40CF 29F7 2265 3197 8E56)

**Comment by saradickinson** [comment]
I'm going to close this issue as it does not seem related to the systemd file in this repo!
