### ISSUE TITLE
how to enable DNSSEC with stubby - which is needed getdns or unbound ?

### ISSUE THREAD

**Issue by blub4747** [getdnsapi/stubby#203]
Hello community,

I am trying to run (DoT) on a instance Stubby on a Raspberyy Pi with Buster as the OS
When reading the the yml file the instructions are confusing regarding the unbound.
Is unbound is necessary to run DNSSEC in combination with (DoT) .

For now I did install on top of Stubby also getdns to get stubby resolve by itself. 
How ever I can see any getdns folder where getdns could store any of its configurations.

**Comment by saradickinson** [comment]
No, you can configure Stubby to perform DNSSEC directly just by uncommenting the line:

**Comment by saradickinson** [comment]
I'm reviewing old issues and am closing this now as I hope the response answered the question. Please re-open if needed.
