### ISSUE TITLE
error: Could not bind on given addresses: File exists

### ISSUE THREAD

**Issue by georgehaws** [getdnsapi/stubby#211]
Dear Mr. Stubbs:

I am loving Stubby on Linux!  It's working perfectly for me there.  So, I thought I would avail myself of Stubby on my Windows 10 (Home) partition.

I'm getting this error message when running the program from CMD as instructed.  Running as Admin does not change the error output:

> C:\WINDOWS\system32>"C:\Program Files\Stubby\stubby.exe" -l
> [03:31:07.162621] STUBBY: Read config from file C:\Program Files\Stubby\stubby.yml
> error: Could not bind on given addresses: File exists

So, I suppose it is good to know that the file exists.  Can any of you fine fellows do me a square and confirm that I too exist?  It's getting lonely in here, and I haven't been able to find myself anywhere...

Thank you!

**Comment by wtoorop** [comment]
Hello George,

I think this means something else is occupying port 53 on 127.0.0.1.  Could you run:
```
netstat -ab
```
and look for processes listening on port 53?
Thanks!

**Comment by georgehaws** [comment]
Ah!

wtoorop, you are the man, and I am a fool.  I had forgotten that I already had DNSCrypt running as a service, so that was listening on the loopback interface @ 127.0.0.1.

Everything is up and running now.  I just needed to disable DNSCrypt (which is a great little piece of software, I just wanted to use TLS instead).

WireShark is now detecting zilch on port 53, lots of encrypted TLS on port 853.  Verizon is probably unhappy about this; Mission Accomplished.

Sincerely your random dood,

George

**Comment by georgehaws** [comment]
BTW, Mr. Toorop:

I just wanted to say, since everything is up and running now: this is freaking amazing.  I'm looking at all the TLS on 853 and I could swear that my browsing is now a lot faster.  Web pages are loading almost instantaneously.  I wonder if that's because Verizon was busy hoovering up packets and introducing latency?  Wouldn't put it past them.

Thanks a million for this!

Best regards,

George

**Comment by wtoorop** [comment]
Excellent! Good to hear! Your welcome :)
Kind regards,
-- Willem
