### ISSUE TITLE
Stubby does not work on Windows10 1909

### ISSUE THREAD

**Issue by Taranis01** [getdnsapi/stubby#213]
I just had a fresh windows 1903 64bit Installation and updated it to 1909.
Now when when i installed stubby and tried to start it i get a blue message overlay by Windows saying: "This app can not be run on the PC.
Contact the software publisher to find a suitable version for your PC"
[Screenshot](https://i.ibb.co/SQ3fgHg/stubby.jpg)

At least on Win10 1809 i had no problems.
Stubby Windows Version 0.2.6

**Comment by stubbydns** [comment]
Works fine for me on 1909 after changing user account control settings to "never notify" and disabling Windows smartscreen. You also might want to make sure you have all Microsofts visual C++ runtimes installed.

**Comment by Taranis01** [comment]
@CarlTuckerson i am using the 64-bit installer. 
however our input brought me to try out the zip-file version and the stubby.exe there does work on my PC. So i replaced the installed files with the files from the zip file. Thanks
