### ISSUE TITLE
Problem with DNSSEC

### ISSUE THREAD

**Issue by udopt** [getdnsapi/stubby#215]
Hi,

I would like to get DNSSEC with stubby working.

Currently, when I directly use my custom DNS-Server, dig yields the `ad` flag if the domain supports DNSSEC. When I use stubby, there is no `ad` flag.

For DNSSEC, I have set the following option in `stubby.yml`:
```
dnssec_return_status: GETDNS_EXTENSION_TRUE
```

Since stubby is run by systemd, I have created `/var/cache/stubby` and set it as appdata_dir:
```
appdata_dir: "/var/cache/stubby"
```

Also, the user `stubby` has full access to that directory:
```
$ ls -ld /var/cache/stubby/
drwxrwx--- 2 root stubby 4096 Dez 14 11:02 /var/cache/stubby/
```

According the the status message, DNSSEC should be working, but unfortunately, it is not:
```
$ sudo systemctl status stubby.service 
● stubby.service - DNS Privacy Stub Resolver
   Loaded: loaded (/lib/systemd/system/stubby.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-12-14 13:24:50 CET; 6min ago
     Docs: https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Daemon+-+Stubby
 Main PID: 9079 (stubby)
    Tasks: 1 (limit: 4915)
   Memory: 1.7M
   CGroup: /system.slice/stubby.service
           └─9079 /usr/bin/stubby

Dez 14 13:24:50 Z systemd[1]: Started DNS Privacy Stub Resolver.
Dez 14 13:24:50 Z stubby[9079]: [12:24:50.117975] STUBBY: Read config from file /etc/stubby/stubby.yml
---> Dez 14 13:24:50 Z stubby[9079]: [12:24:50.118919] STUBBY: DNSSEC Validation is ON
Dez 14 13:24:50 Z stubby[9079]: [12:24:50.118930] STUBBY: Transport list is:
Dez 14 13:24:50 Z stubby[9079]: [12:24:50.118933] STUBBY:   - TLS
Dez 14 13:24:50 Z stubby[9079]: [12:24:50.118936] STUBBY: Privacy Usage Profile is Strict (Authentication required)
Dez 14 13:24:50 Z stubby[9079]: [12:24:50.118939] STUBBY: (NOTE a Strict Profile only applies when TLS is the ONLY transport!!)
Dez 14 13:24:50 Z stubby[9079]: [12:24:50.118942] STUBBY: Starting DAEMON....
```

**Comment by saradickinson** [comment]
You need to use `dnssec: GETDNS_EXTENSION_TRUE` to force DNSSEC to work, the log is misleading here and needs fixing....

**Comment by udopt** [comment]
Thank you very much for your help.

I have now tried `dnssec: GETDNS_EXTENSION_TRUE` as well as `dnssec: GETDNS_EXTENSION_TRUE` **plus** `dnssec_return_status: GETDNS_EXTENSION_TRUE`. In both cases I observe the exactly the same problem.

**Comment by saradickinson** [comment]
Can you be a bit more specific? For example if have stubby running on localhost using a config with `dnssec: GETDNS_EXTENSION_TRUE` and I do the following two queries 
1) dig @8.8.8.8 getdnsapi.net 
2) dig @127.0.0.1 getdnsapi.net 
both responses have the AD bit set. 
Note also that when stubby is configured to perform DNSSEC it does the validation locally by querying for all the necessary records. dig is simply performing one query to the recursive resolver.

**Comment by udopt** [comment]
Thank you again, your `dig` command with the explicit name servers helped me!

As it turns out, my system DNS server was `127.0.0.53` (probably due to `systemd`), so I needed to set this IP in the `stubby.yml` under `listen_addresses`. Having done that, using `dnssec: GETDNS_EXTENSION_TRUE` **or** `dnssec_return_status: GETDNS_EXTENSION_TRUE` **or** both results in the `AD` bit.

I am happy that it works now, though it puzzles me that using only `dnssec_return_status: GETDNS_EXTENSION_TRUE` seems to be enough. (`dig` has a connection time out if stubby is disabled, so it seems that there is no other DNS resolver involved.)

**Comment by saradickinson** [comment]
Glad you got this working! We recommend `dnssec: GETDNS_EXTENSION_TRUE` because that will hard fail if there are problems retrieving, storing or accessing the root DNSSEC keys, `dnssec_return_status:` won't do this....

**Comment by saradickinson** [comment]
I'm reviewing old issues and am closing this now as I hope the response answered the question. Please re-open if needed.
