### ISSUE TITLE
miss type in stubby/src/sldns/sbuffer.h ?

### ISSUE THREAD

**Issue by kometchtech** [getdnsapi/stubby#216]
I thought it was an issue on the getdns side, but write it here.

If you make with the build option described below, you will get a build error or a typo in `sbuffer.h`.

```
In file included from /usr/src/stubby/src/sldns/sbuffer.c:15:
/usr/src/stubby/src/sldns/sbuffer.h:288:41: error: unknown type name 'ssize_t'; did you mean 'size_t'?
  288 | sldns_buffer_skip(sldns_buffer *buffer, ssize_t count)
      |                                         ^~~~~~~
      |                                         size_t
make[2]: *** [stubby/CMakeFiles/stubby.dir/build.make:89: stubby/CMakeFiles/stubby.dir/src/sldns/sbuffer.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1646: stubby/CMakeFiles/stubby.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```
build option.
```
cmake \
        -DCMAKE_INSTALL_PREFIX=/tmp/root/usr/local \
        -DENABLE_STUB_ONLY=ON \
        -DUSE_LIBUV=ON \
        -DUSE_LIBEV=ON \
        -DUSE_LIBEVENT2=ON \
        -DUSE_LIBIDN2=ON \
        -DBUILD_STUBBY=ON \
        -DCMAKE_C_FLAGS:STRING="${CFLAGS}" \
        ..
```

https://github.com/getdnsapi/stubby/blob/a35cbc93f0951db13161278888b06e8cd933bd84/src/sldns/sbuffer.h#L288

**Comment by saradickinson** [comment]
`ssize_t` is a posix extension so I think the issue is a missing #ifdef for Windows (I assume you are building in Visual Studio?). fca08b0c2d4bc4f8aa22c71aba00bc1bf7fc86ef should fix this

**Comment by Desuuuu** [comment]
This issue happens on Alpine Linux.

According to the [POSIX documentation](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_types.h.html), `ssize_t` is defined in `sys/types.h`. Adding the include solves the problem.
