### ISSUE TITLE
cmake fails Getdns version check for 1.6.0-beta.1

### ISSUE THREAD

**Issue by tomporter518** [getdnsapi/stubby#223]
When attempting to execute stubby's cmake against an installed, self-build Getdns, the following error occurs:

`pi@grey:~/Projects/getdns/stubby $ cmake . -DCMAKE_BUILD_TYPE=Release
CMake Error at /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find Getdns: Found unsuitable version "#define GETDNS_VERSION
  "1.6.0-beta.1"", but required is at least "1.5.0" (found
  /usr/local/lib/libgetdns.so)
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindGetdns.cmake:65 (find_package_handle_standard_args)
  CMakeLists.txt:90 (find_package)`

Temporarily removing REQUIRED from line 118 of CMakeList.txt allows cmake to complete. Thereafter, the built stubby seems to work as expected against 1.6.0-beta.1 of Getdns.

Note: The version detected above shows '#define GETDNS_VERSION', when I suspect it should not and may actually be a problem in Getdns.

**Comment by tomporter518** [comment]
Upon inspecting FindGetdns.cmake, line:
`58     string(REGEX REPLACE "^.*GETDNS_VERSION \"([0-9.]+)\".*$" "\\1" GETDNS_VERSION "${GETDNS_H}")`
does not seem to be able to handle '-beta.1' and the REGEX fails to replace '#define GETDNS_VERSION'. Without knowing the potential values, it's not easy to discern a generic suggestion for the REGEX.

**Comment by banburybill** [comment]
Thanks for spotting this. I'd forgotten about semantic versioning pre-release and build suffixes; luckily, the semantic versioning specification is explicit about what can be in them, so I've modified the regex to ignore them.
