### ISSUE TITLE
Option round_robin_upstreams 0 is not working

### ISSUE THREAD

**Issue by morton-f** [getdnsapi/stubby#232]
Edited. 
Stubby 0.2.2 Linux Mint and  0.2.5 Debian Testing. After inserting Cloudflare servers at the start of the upstream servers list, setting _round_robin_upstreams_ to 0 and **restarting OS**, stubby using only default servers, never Clouflare. So, three default servers should be commented out after inserting CloudFlare servers in the _upstream_recursive_servers_ section.

**Comment by morton-f** [comment]
Additional info, after the initial setup and executing command _sudo systemctl restart stubby_ _round_robin_upstreams 0_ option working as expected (using only Cloudflare servers). After restarting OS (shutdown -r) stubby started to use only 145.100.185.15 server. After executing _sudo systemctl restart stubby_ stubby started using only Cloudflare servers again.
OS LMDE 4, stubby 0.2.5

**Comment by wtoorop** [comment]
I think this happened because stubby is started when the network is not yet available.
Stubby will currently stick with a working upstream once it found one.
More recent stubbies should not have this issue because of #197 (resolved in #221) I believe.
Could you try if stubby-0.3.0 resolves the issue for you?

**Comment by morton-f** [comment]
I'll try to compile 0.3.0 later. For now, delay is:
```
systemd-analyze critical-chain stubby.service
stubby.service @2.275s
└─network-online.target @2.230s
  └─network.target @2.221s
    └─NetworkManager.service @1.737s +444ms
      └─dbus.service @1.660s
        └─basic.target @1.629s
          └─sockets.target @1.620s
            └─acpid.socket @1.614s
              └─sysinit.target @1.546s
                └─systemd-timesyncd.service @1.471s +60ms
                  └─systemd-tmpfiles-setup.service @946ms +482ms
                    └─systemd-journal-flush.service @864ms +75ms
                      └─var-log.mount @810ms +34ms
                        └─local-fs-pre.target @793ms
                          └─systemd-tmpfiles-setup-dev.service @736ms +43ms
                            └─kmod-static-nodes.service @416ms +222ms
                              └─systemd-journald.socket @408ms
                                └─system.slice @227ms
                                  └─-.slice @225ms
```
The issue had been mitigated (after full restart system is using 1.0.0.1) when I inserted 2 lines in the _/lib/systemd/system/stubby.service_
```
[Service]
......
Restart=on-failure
RestartSec=1
```
After full restart system is using 1.0.0.1.

**Comment by morton-f** [comment]
Preparing the stubby compilation I installed (probably unnecessarily) getdns-utils 1.5.1-1+b2  and restarted the system. After that the issue definitely gone so the compilation of stabby on that system (debian testing) became inconclusive. For now I'm stalled out...

**Comment by morton-f** [comment]
I install stubby 0.2.5 on two different systems, debian 10 and xubuntu 19.10 and there is no issue with round robin switch on both of them. Mentioned above two systems (issue was confirmed during two consecutive days across at least 5 reboots each) are working as expected now even with standard setup restored. All systems are on the same network.

>I think this happened because stubby is started when the network is not yet available.

Thank you for the suggestion! It's seems not the case here (please see code below): stubby.service is on 0.002 sec  after network-online.target unit.  May be the issue was caused by some instability Cloudflare server in a region? ... just a guess...

Should the issue be closed because it contains little more than observations...

```
11:16:48 d10 systemd[1]: Starting Network Time Synchronization...
11:16:48 d10 systemd[1]: Started Network Time Synchronization.
11:16:48 d10 systemd[1]: Reached target System Time Synchronized.

11:16:52 networking.service - Raise network interfaces
 Process: 405 ExecStart=/sbin/ifup -a --read-environment (code=exited, status=0/SUCCESS)
 Main PID: 405 (code=exited, status=0/SUCCESS)

stubby.service 
   Active: active (running) since  11:16:57
11:17:00 d10 stubby[600]: [09:17:00.129259] STUBBY: Read config from file /etc/stubby/stubby.yml
11:17:00 d10 stubby[600]: [09:17:00.131262] STUBBY: Starting DAEMON....
```

**Comment by wtoorop** [comment]
Yes, I'll close the ticket, but thanks anyway for sharing your observations with us! Much appreciated.
