### ISSUE TITLE
Strange answer by stubby status

### ISSUE THREAD

**Issue by Fede068** [getdnsapi/stubby#243]
Hy guys, I've pi-hole with stubby installed on my Raspberrypi 3+ which is working well. I discover some strange notification after checking the status. Please compare as follow:

pi@pi-hole:~ $ sudo systemctl status stubby
● stubby.service - stubby DNS resolver
   Loaded: loaded (/lib/systemd/system/stubby.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-04-15 12:19:36 CEST; 23h ago
 Main PID: 19125 (stubby)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/stubby.service
           └─19125 /usr/local/bin/stubby

Apr 16 07:32:15 pi-hole stubby[19125]: Could not get qname from query: A helper function for dicts had a name argument that for a name that is not in the dict.
Apr 16 07:32:15 pi-hole stubby[19125]: Could not get qname from query: A helper function for dicts had a name argument that for a name that is not in the dict.
Apr 16 07:32:15 pi-hole stubby[19125]: Could not get qname from query: A helper function for dicts had a name argument that for a name that is not in the dict.
Apr 16 07:32:15 pi-hole stubby[19125]: Could not get qname from query: A helper function for dicts had a name argument that for a name that is not in the dict.
Apr 16 07:32:15 pi-hole stubby[19125]: Could not get qname from query: A helper function for dicts had a name argument that for a name that is not in the dict.
Apr 16 10:51:09 pi-hole stubby[19125]: Could not get qname from query: A helper function for dicts had a name argument that for a name that is not in the dict.
Apr 16 10:51:09 pi-hole stubby[19125]: Could not get qname from query: A helper function for dicts had a name argument that for a name that is not in the dict.
Apr 16 10:51:09 pi-hole stubby[19125]: Could not get qname from query: A helper function for dicts had a name argument that for a name that is not in the dict.
Apr 16 10:51:09 pi-hole stubby[19125]: Could not get qname from query: A helper function for dicts had a name argument that for a name that is not in the dict.
Apr 16 10:51:09 pi-hole stubby[19125]: Could not get qname from query: A helper function for dicts had a name argument that for a name that is not in the dict.

pi@pi-hole:~ $ sudo stubby status
[09:44:20.851968] STUBBY: Read config from file /usr/local/etc/stubby/stubby.yml
[09:44:20.856403] STUBBY: DNSSEC Validation is OFF
[09:44:20.857534] STUBBY: Transport list is:
[09:44:20.858306] STUBBY:   - TLS
[09:44:20.859132] STUBBY: Privacy Usage Profile is Strict (Authentication required)
[09:44:20.859943] STUBBY: (NOTE a Strict Profile only applies when TLS is the ONLY transport!!)
[09:44:20.860678] STUBBY: Starting DAEMON....
^C
pi@pi-hole:~ $

Why I don´t get the same answer? What does it mean "Could not get qname from ..."?

Pls help, thank you in advance!

**Comment by wtoorop** [comment]
Looks like a non-DNS message was received by your Stubby deamon

**Comment by saradickinson** [comment]
I'm reviewing issues and am closing this now as I hope the response answered the question. Please re-open if needed.
