### ISSUE TITLE
Stuppy service not starting

### ISSUE THREAD

**Issue by ajaikumarnadar** [getdnsapi/stubby#252]
whenever I try to start the stubby service.. I get the following errors in logs

Sun Jun  7 13:12:09 2020 daemon.err stubby[14322]: Error relocating /usr/lib/libgetdns.so.10: ENGINE_by_id: symbol not found
Sun Jun  7 13:12:09 2020 daemon.err stubby[14322]: Error relocating /usr/lib/libgetdns.so.10: ENGINE_free: symbol not found
Sun Jun  7 13:12:09 2020 daemon.err stubby[14322]: Error relocating /usr/lib/libgetdns.so.10: ENGINE_set_default: symbol not found
Sun Jun  7 13:12:09 2020 daemon.err stubby[14322]: Error relocating /usr/lib/libgetdns.so.10: ENGINE_finish: symbol not found
Sun Jun  7 13:12:09 2020 daemon.err stubby[14322]: Error relocating /usr/lib/libgetdns.so.10: ENGINE_load_builtin_engines: symbol not found

Please help !

**Comment by saradickinson** [comment]
Looks like stubby cannot find the libgetdns library at run time:
1) Are you sure libgetdns exists in that location
2) can you run `ldd` on the stubby executable
3) Can you clarify what OS you are on and how you installed and built both stubby and getdns?

**Comment by ajaikumarnadar** [comment]
```
1.
root@X-WRT:~# ls -al /usr/lib/libgetdns.so.10
lrwxrwxrwx    1 root     root            19 Jun  7 12:28 /usr/lib/libgetdns.so.10 -> libgetdns.so.10.1.2


2.
root@X-WRT:/# ldd /usr/sbin/stubby
        /lib/ld-musl-mipsel-sf.so.1 (0x77f03000)
        libyaml-0.so.2 => /usr/lib/libyaml-0.so.2 (0x77edf000)
        libgetdns.so.10 => /usr/lib/libgetdns.so.10 (0x77e83000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x77e5f000)
        libc.so => /lib/ld-musl-mipsel-sf.so.1 (0x77f03000)
        libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x77dd4000)
        libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x77bb0000)
Error relocating /usr/lib/libgetdns.so.10: ENGINE_by_id: symbol not found
Error relocating /usr/lib/libgetdns.so.10: ENGINE_free: symbol not found
Error relocating /usr/lib/libgetdns.so.10: ENGINE_set_default: symbol not found
Error relocating /usr/lib/libgetdns.so.10: ENGINE_finish: symbol not found
Error relocating /usr/lib/libgetdns.so.10: ENGINE_load_builtin_engines: symbol not found

```

3.
I am running stubby in X-WRT, a OpenWRT based firmware. It has package manager `opkg` by which I installed the stubby packages and other dependencies might have got installed automatically.

Thanks for your reply :)

**Comment by ajaikumarnadar** [comment]
Also getdns version is 1.5.2-2

**Comment by johndickinson** [comment]
Can you confirm that /usr/lib/libgetdns.so.10.1.2 exists?

**Comment by ajaikumarnadar** [comment]
```
root@X-WRT:~# ldd /usr/lib/libgetdns.so.10.1.2
        ldd (0x77e61000)
        libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x77d7a000)
        libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x77b56000)
        libc.so => ldd (0x77e61000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x77b32000)
Error relocating /usr/lib/libgetdns.so.10.1.2: ENGINE_by_id: symbol not found
Error relocating /usr/lib/libgetdns.so.10.1.2: ENGINE_free: symbol not found
Error relocating /usr/lib/libgetdns.so.10.1.2: ENGINE_set_default: symbol not found
Error relocating /usr/lib/libgetdns.so.10.1.2: ENGINE_finish: symbol not found
Error relocating /usr/lib/libgetdns.so.10.1.2: ENGINE_load_builtin_engines: symbol not found
```

**Comment by johndickinson** [comment]
Have you tried reinstalling getdns and stubby? It worked here: https://forum.openwrt.org/t/stubby-issues-out-of-nowhere/36814/2

**Comment by ajaikumarnadar** [comment]
Even after reinstall of both getdns and stubby, still I am getting same error.

```
root@X-WRT:~# stubby
Error relocating /usr/lib/libgetdns.so.10: ENGINE_by_id: symbol not found
Error relocating /usr/lib/libgetdns.so.10: ENGINE_free: symbol not found
Error relocating /usr/lib/libgetdns.so.10: ENGINE_set_default: symbol not found
Error relocating /usr/lib/libgetdns.so.10: ENGINE_finish: symbol not found
Error relocating /usr/lib/libgetdns.so.10: ENGINE_load_builtin_engines: symbol not found
```

**Comment by saradickinson** [comment]
To be honest, this looks like a packaging issue for OpenWRT.... you might be better off contacting someone who has worked on that stubby package e.g. @jonathanunderwood (https://github.com/jonathanunderwood)?

**Comment by jonathanunderwood** [comment]
I package stubby for OpenWRT, but have no sight into X-WRT (in fact, I never knew about it until just now!). This looks like something X-WRT specific, given that stubby is working fine for many users in OpenWRT.

**Comment by ajaikumarnadar** [comment]
Actually, X-WRT is a fork of OpenWRT firmware.
(https://github.com/x-wrt/x-wrt)

And @ptpt52 is founder / developer of X-WRT.

**Comment by saradickinson** [comment]
@jonathanunderwood  thanks for the response :-) 

@ajaikumarnadar hope you can resolve this with the X-WRT folks!

**Comment by ajaikumarnadar** [comment]
I tried reaching the developer of X-WRT for help, but he's unable to help with this...

I think the issue that I am facing is very much related to the below link...

https://github.com/getdnsapi/getdns/issues/401

If you have a look at the above link, common keywords that match with my issue are "ENGINE_by_id", "ENGINE_load_builtin_engines", etc.


```
Sat Jul  4 14:24:37 2020 daemon.err stubby[29374]: Error relocating /usr/lib/libgetdns.so.10: ENGINE_by_id: symbol not found
Sat Jul  4 14:24:37 2020 daemon.err stubby[29374]: Error relocating /usr/lib/libgetdns.so.10: ENGINE_free: symbol not found
Sat Jul  4 14:24:37 2020 daemon.err stubby[29374]: Error relocating /usr/lib/libgetdns.so.10: ENGINE_set_default: symbol not found
Sat Jul  4 14:24:37 2020 daemon.err stubby[29374]: Error relocating /usr/lib/libgetdns.so.10: ENGINE_finish: symbol not found
Sat Jul  4 14:24:37 2020 daemon.err stubby[29374]: Error relocating /usr/lib/libgetdns.so.10: ENGINE_load_builtin_engines: symbol not found
Sat Jul  4 14:24:37 2020 daemon.info procd: Instance stubby::stubby s in a crash loop 9 crashes, 0 seconds since last crash
```
