### ISSUE TITLE
Latest release

### ISSUE THREAD

**Issue by jawadcogilent** [getdnsapi/stubby#254]
Hi,

Stubby 0.3.0 is not marked as Latest Release.

Should we use 0.2.6 version?

Regards

**Comment by saradickinson** [comment]
This was an oversight - I've fixed the release listing. Please note that 0.3.0 is the latest release but it does migrate the build system to use `cmake` (as the companion `getdns` release did), please see the release notes here:
https://getdnsapi.net/releases/getdns-1-6-0/
