### ISSUE TITLE
Systemd Service in raspbian Buster don't find stubby.yml

### ISSUE THREAD

**Issue by matkoh58** [getdnsapi/stubby#259]
Hello,
I installed package stubby in raspbian Buster. When I start stubby.service, the configuration file /etc/stubby/stubby.yml is not found. When I start stubby manual with
`sudo stubby -i`
it finds and execute the stubby.yml.

I changed the stubby.service to find the configuration:
`ExecStart=/usr/bin/stubby -C /etc/stubby/stubby.yml`
but this leads to error
`Could not parse config file "/etc/stubby/stubby.yml": Permission denied`

I can deactivate DynamicUser in stubby.service and then stubby works as a service. But it is executed as root and this is not a good solution.

So, where I have to place the stubby.yml, so the service can find it and execute as DynamicUser?

Matthias

**Comment by saradickinson** [comment]
Closing this due to age and lack of follow up from us (sorry).... please try the latest release which includes updates to the systemd service file and re-open if necessary.
