### ISSUE TITLE
stubby.yml should be installed under $(DESTDIR)

### ISSUE THREAD

**Issue by ArchangeGabriel** [getdnsapi/stubby#26]
In https://github.com/getdnsapi/stubby/blob/0cbd46ea6d0da727c42b0890d498366cd2b1ec2c/Makefile.am#L18, the config file is installed in ${stubbyconfdir}, but this folder might not exist:
```
test -f /etc/stubby/stubby.yml || \
	/usr/bin/install -c -m 644 ./stubby.yml.example /etc/stubby/stubby.yml
/usr/bin/install: cannot create regular file '/etc/stubby/stubby.yml': No such file or directory
```

That’s because the folder was created under $(DESTDIR), which is not used here.

**Comment by ArchangeGabriel** [comment]
Oh, and in fact the problem rises even above that: this does not respect `DESTDIR`.

**Comment by saradickinson** [comment]
Hi, thanks for the report. I think PR #26 should fix this.

**Comment by ArchangeGabriel** [comment]
PR #33, but yes it works. ;)
