### ISSUE TITLE
Problem with "listen_addresses"

### ISSUE THREAD

**Issue by maidmeow4** [getdnsapi/stubby#261]
Hi, I'm setting up Stubby as a IPv4 & IPv6 dual-stack DNS server inside my LAN, I set `listen_addresses` to these values :
```yaml
listen_addresses:
  - 0.0.0.0
  - 0::0
```
with this config Stubby won't listen on TCP6 port, any DNS queries sent with IPv6 just failed :
```
netstat -antup | grep stubby
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      6349/stubby
udp        0      0 0.0.0.0:53              0.0.0.0:*                           6349/stubby
udp6       0      0 :::53                   :::*                                6349/stubby
```
```
kdig -d twitter.com @IPv6_address +tcp
;; DEBUG: Querying for owner(twitter.com.), class(1), type(1), server(IPv6_address), port(53), protocol(TCP)
;; WARNING: can't connect to IPv6_address@53(TCP)
;; ERROR: failed to query server IPv6_address@53(TCP)
```
Is there something wrong with my config ?
OS: Fedora 32 (aarch64) on Raspberry Pi 3

**Comment by saradickinson** [comment]
You need to set the listen_addresses to be localhost (as they are in the default config)
``` 
listen_addresses:
  - 127.0.0.1
  - 0::1
```
https://github.com/getdnsapi/stubby/blob/develop/stubby.yml.example

**Comment by wtoorop** [comment]
@saradickinson , 0.0.0.0 and ::0 are a way to indicate to bind to all addresses.
I vaguely remember something in the lines of binding to IPv6 0::0 would result in also binding to all IPv4 address, but I'd have to look into it.

**Comment by wtoorop** [comment]
@maidmeow4 Don't ask me why, but indeed when listening to only `0::0`, stubby will also listen to ANY address on IPv4 both UDP and TCP.  Specifying the IPv4 ANY address basically blocked opening the IPv6 TCP listening socket.

**Comment by maidmeow4** [comment]
@wtoorop Hi, tried `0::0` only and it does work both with IPv4 and IPv6, thanks!
