### ISSUE TITLE
win 10 32bit .. 

### ISSUE THREAD

**Issue by CHazz** [getdnsapi/stubby#263]
hi i have problem with stubby .. after random time .. freeze and stop working (no any one log).. i try change openssl and yaml DLLs with new but no change :/ on x64 and debian working great .. i no have chance compile latest beta for test :(  using only linux, and here working perfect :)

**Comment by saradickinson** [comment]
Closing this as housekeeping due to age and lack of follow up from us (sorry).... Please re-open if needed.
