### ISSUE TITLE
Run Stubby as a windows service

### ISSUE THREAD

**Issue by wellloaded** [getdnsapi/stubby#266]
There's currently a way to run Stubby as a scheduled task under windows ad mentioned in this ticket:
https://github.com/getdnsapi/stubby/issues/37

however this approach is nowhere as effective as having stubby running as a service natively. Specifically the current Scheduled Task approach is not sleep/hibernation friendly and requires a manual interaction regardless after windows is waken-up. If you ask me moving into a service is not a solution either but it can perform well if the right function calls are made. e.g. https://stackoverflow.com/questions/11367318/how-do-windows-services-behave-when-entering-waking-up-from-sleep-or-hibernate-m

Thanks

**Comment by saradickinson** [comment]
If you take a look in the develop branch you will see that we have the basics of Stubby as a full Windows service working but we are still tinkering with the finer details (file locations, service options). Please feel free to review.

**Comment by saradickinson** [comment]
Closing as released in 0.4.0
