### ISSUE TITLE
Stubby active / WARNING: recursion requested but not available

### ISSUE THREAD

**Issue by Q7ak5** [getdnsapi/stubby#267]
Stubby ia active (checked by "service stubby status"), but any test by dig command fails:

; <<>> DiG 9.11.5-P4-5.1+deb10u2-Raspbian <<>> @127.0.0.1 www.startpage.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 63787
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;www.startpage.com.             IN      A

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: So Sep 06 17:53:19 CEST 2020
;; MSG SIZE  rcvd: 35

If I replace stubby server with an upstream server DNSSEC validation works fine, but no encryption by DoT.

**Comment by saradickinson** [comment]
Can you provide your stubby config? You are seeing a SERVFAIL with ```WARNING: recursion requested but not available``` rather than a timeout which makes me think that there may be a problem with the config....  Also, please try to check in the log file for the stubby service to see what it is reporting as an error.

**Comment by saradickinson** [comment]
Closing this issue due to age and no additional details provided
