### ISSUE TITLE
为什么总是报错证书错误

### ISSUE THREAD

**Issue by RomanSmile** [getdnsapi/stubby#271]
``l@l:~$ kdig -d @89.233.43.71 +tls-host=unicast.censurfridns.dk www.baidu.com
;; DEBUG: Querying for owner(www.baidu.com.), class(1), type(1), server(89.233.43.71), port(853), protocol(TCP)
;; DEBUG: TLS, imported 127 system certificates
;; DEBUG: TLS, received certificate hierarchy:
;; DEBUG:  #1, CN=unicast.censurfridns.dk
;; DEBUG:      SHA-256 PIN: INSZEZpDoWKiavosV2/xVT8O83vk/RRwS+LTiL+IpHs=
;; DEBUG:  #2, C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3
;; DEBUG:      SHA-256 PIN: YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg=
;; DEBUG: TLS, skipping certificate PIN check
;; DEBUG: TLS, The certificate is NOT trusted. The revocation or OCSP data are old and have been superseded. 
;; WARNING: TLS, handshake failed (Error in the certificate.)
;; ERROR: failed to query server 89.233.43.71@853(TCP)

**Comment by saradickinson** [comment]
Stubby doesn't use OCSP so it still connections fine and we don't run the unicastcensurfridns.dk servers, so I've passed this report onto admin@censurfridns.dk....

**Comment by RomanSmile** [comment]
@saradickinson 
 感谢你的解答，再次感谢！！！

**Comment by tykling** [comment]
hello @RomanSmile this has been fixed, thank you for the report!

**Comment by RomanSmile** [comment]
@tykling 这个项目给世界上所有人带来安全，反馈信息是每个人应该做的事情！
