### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by jonathanunderwood** [getdnsapi/stubby#282]
It's been a while since there was a release of Stubby, and there's a bunch of useful changes gone in to master since. Any chance of pushing a release soon?

**Comment by saradickinson** [comment]
Yes - a release is overdue....! @wtoorop let's plan this

**Comment by saradickinson** [comment]
@wtoorop and I just met and we should have a 0.4.0 stubby release candidate ready next week

**Comment by saradickinson** [comment]
Closing as 0.4.0 was released.
