### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by serioususer** [getdnsapi/stubby#283]
just built getdns following the [instructions](https://github.com/getdnsapi/getdns#building)

after this i cloned this repo and tried to build it - i got some errors like libsystemd not found.
but i could fix this by installing following packages:
sudo apt install libsystemd-dev
sudo apt install libudev-dev

after this i tried to build it again with cmake but some more errors occour.
It seems that cmake cant find some libaries:
_CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Getdns (missing: GETDNS_LIBRARIES GETDNS_INCLUDE_DIR)
  (Required is at least version "1.5.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindGetdns.cmake:109 (find_package_handle_standard_args)
  CMakeLists.txt:181 (find_package)_

I build getdns correctly and i can you getdns_query.
I cloned both repos in my homedir.

Does anybody know how to link the libaries to the right place?

**Comment by saradickinson** [comment]
You have two options
1) you can use the configure options to the `stubby` make command to set the variables to point to your installed getdns library e.g `-DGETDNS_LIBRARY=/usr/local/lib/libgetdns.dylib -DGETDNS_INCLUDE_DIR=/usr/local/include` depending on where your library was actually installed. 
2) You can alternatively build stubby directly as part of the getdns build by using the `-DBUILD_STUBBY=ON` cmake option on the getdns cmake command.

**Comment by serioususer** [comment]
this worked great - thank you :=)

solution was: -DGETDNS_LIBRARY=path/to/libgetdns.so -DGETDNS_INCLUDE_DIR=path/to/getdns/folder

But now i have another problem.

i tried to start stubby in the background:
```
sudo stubby -g
[13:59:53.293664] STUBBY: Stubby version: Stubby 0.3.0
WARNING: No Stubby config file found... using minimal default config (Opportunistic Usage)
Could not write pid to "/usr/local/var/run/stubby.pid": No such file or directory
```

i also checked the process:
```
sudo systemctl status stubby
* stubby.service
   Loaded: masked (Reason: Unit stubby.service is masked.)
   Active: inactive (dead)
```

i found in the internet that a process is masked if the application file is 0 bytes..but i cant confirm this..

the strange thing is that this works:
`dig @127.0.0.1 ix.de`
but if i change my resolver in _/etc/resolve.conf_ i am not able to perform any successful queries.

**Comment by pataquets** [comment]
@serioususer: you can build and run stubby from source easily using [Docker](https://github.com/getdnsapi/stubby/blob/develop/contrib/docker/README.md).

**Comment by saradickinson** [comment]
I'm closing this issue as housekeeping. If the issue persists with the latest release please re-open.
