### ISSUE TITLE
getdns includes stubby 0.4.0, but no such release here

### ISSUE THREAD

**Issue by pemensik** [getdnsapi/stubby#287]
Because stubby has got its own versioning and repository, we decided in Fedora to split stubby from main getdns package into separate package. But I don't see release here for stubby, last release is still 0.3.0.

Is it unsupported to package stubby from separate sources from this repository? Could be release tagged also here?

**Comment by pemensik** [comment]
Ah, sorry for the noise. The tag is there, but no comments on release notes is present. It is not displayed well by github.

**Comment by pemensik** [comment]
https://github.com/getdnsapi/stubby/releases/tag/v0.4.0

It is there, but not very visible. I guess it can be improved only next release.

**Comment by saradickinson** [comment]
Sorry - we missed adding the release notes for 0.4.0 - done now.
