### ISSUE TITLE
Wiki - instructions for saving current DNS config

### ISSUE THREAD

**Issue by mi-hol** [getdnsapi/stubby#29]
Instructions for Windows on [https://dnsprivacy.org/wiki/display/DP/Windows+installer+for+Stubby](url)
say in section: Modify your upstream resolvers 
'It might be useful to note your existing default nameservers before making this change!'
and
'If you encounter problems reverse this change to restore your default settings (no DNS Privacy). '
as the installation is done via PowerShell script "C:\Program Files\Stubby\stubby_setdns_windows.ps1" and reset is "C:\Program Files\Stubby\stubby_resetdns_windows.ps1" its not 100% clear from the current wording if the DNS setting get saved by installation and then restored by the reset script.

Looking at the scripts there is currently no backup & restore of DNS setting implemented, but it should be fairly easy to add. Then using backup & restore terms could help people to understand the involved risk better :)

PS: Is it technically feasible to change the 'Wiki' link in github to point to above mentioned wiki?

**Comment by saradickinson** [comment]
Hi, thanks for trying Stubby!

The reason the script does not store the current configuration and then restore it directly is that your DNS configuration is normally specific to the network that you are on (so it changes between home, work and public wifi). The script "C:\Program Files\Stubby\stubby_resetdns_windows.ps1" restores your system to the default settings for the network you are on when you run the script.  I've tried to update the wording on the webpage to make this clearer... let me know if you think this helps. 

I've also added text to the wiki page to direct people to dnsprivacy.org - I can't do a forced redirect, this is the next best thing. Thanks for the idea!

**Comment by mi-hol** [comment]
Thanks Sara, already much easier to understand :)
I'd remove 'Use the same command but with "C:\Program Files\Stubby\stubby_resetdns_windows.ps1" instead to switch back to the default network DNS nameservers.' as its now a kind of duplicate to the next sentence.

**Comment by saradickinson** [comment]
Thanks - yes removed the duplicate. 

The text now says: "In most cases your system will use the 'default' DNS servers that are provided by whatever network you are on at the time. Using the two Powershell comands will be all you need to switch back and forth from Stubby to the default DNS settings for the network you are on. (The scripts don't store any DNS config information because it can change dynamically). "

Hope this look OK.

**Comment by mi-hol** [comment]
Great improvement!
Only one question remains :)
Is the link inside 'If you want to double check what servers you are using right now you can use then follow the instructions below to inspect your system settings.' still correct?

**Comment by saradickinson** [comment]
There was a typo in the anchor - fixed now! Feel to close the issue if you are happy with the response :-)

**Comment by saradickinson** [comment]
Closing as I think the latest changes address this. Re-open if any further issues.

**Comment by mi-hol** [comment]
Thanks Sara, the changes addressed this issue :) 
Sorry for the delay in my response
