### ISSUE TITLE
Uninstall Old Stubby for Windows

### ISSUE THREAD

**Issue by LastRoze** [getdnsapi/stubby#292]
Can someone post me a file for the stubby-0.4.0.90-x64.msi build? because it's stuck in my control panel when I tried to uninstall it. I want to update to the latest version which .97 and already delete the .90-x64 file. thank you.

![image](https://user-images.githubusercontent.com/9519234/125126659-a00a4800-e125-11eb-8109-b0cacd00ce45.png)

**Comment by saradickinson** [comment]
You should be able to install the latest version directly over the top of the existing install - it should overwrite everything so please try that.

**Comment by saradickinson** [comment]
If you need it the stubby-0.4.0.90-x64.msi is now attached to the installer page here:
https://dnsprivacy.org/wiki/download/attachments/6782986/stubby-0.4.0.90-x64.msi?api=v2

**Comment by saradickinson** [comment]
Closing as installer provided
