### ISSUE TITLE
Use standard notation for IPv6 local loopback address  ( ::1 instead of 0::1 )

### ISSUE THREAD

**Issue by shoulders** [getdnsapi/stubby#304]
Within the documentation and config files of stubby you use the address **0::1** for the IPv6 local loopback address (which does work) but I cannot find anywhere else that uses this form, everyone use **::1**

I think these instances should be changed to keep things easier to read unless there is a technical reason for this.

These are a few that I found
README.md
```
listen_addresses:
  - 127.0.0.1
  -  0::1
 ```

stubby.yml.example
https://github.com/getdnsapi/stubby/blob/f105374c9f1475dbbad63bea086e7cf953f7d169/stubby.yml.example#L126

**Comment by ArchangeGabriel** [comment]
See https://github.com/getdnsapi/getdns/issues/358.

**Comment by saradickinson** [comment]
As noted - this is an issue with our parser but I've added a comment directly into the config file to make this clearer

**Comment by saradickinson** [comment]
I'm closing this since the updated text was in 0.4.1 release but also marking as duplicate of the issue raising the underlying problem
