### ISSUE TITLE
Could NOT find Getdns

### ISSUE THREAD

**Issue by trinib** [getdnsapi/stubby#308]
i already installed https://github.com/getdnsapi/getdns but why stubby says can't find it

**Comment by saradickinson** [comment]
Can you please provide more information:
* what platform are you building on
* How and where did you install libgetdns
* what options have you set on `cmake`
* a log of the specific error message you get

The more detail you can provide on your build steps the better chance we have of figuring out the issue!

**Comment by trinib** [comment]
well i install it from repo and working , trying to build it get issues for me , maybe i did install wrong dependencies 

- RasberryPi (bullseye) 

- I used `cmake .` (make without dot don't work) then `make` and then i get the error saying stubby has not found getdns folder that all, sorry i cant give you log screenshot for i have to redo everything from my working set up . but if i have to guess i can if you really need it

- For libgetdns
```
sudo apt-get install -y libgetdns-dev
```

**Comment by saradickinson** [comment]
You can use `cmake . -LA` to get a list of all the variables used for building and in this list you will see 2 items:
````
GETDNS_INCLUDE_DIR:PATH=GETDNS_INCLUDE_DIR-NOTFOUND
GETDNS_LIBRARY:FILEPATH=GETDNS_LIBRARY-NOTFOUND
````
If your system can't find them in any of the 'normal' locations then you need to make those variables point to wherever files where actually installed - for the headers (search for `getdns.h`) and the library (search for `libgetdns`). So you need to specify them after the `cmake` command like this:
```
cmake -DGETDNS_INCLUDE_DIR=<path to headers>  -DGETDNS_LIBRARY=<path to library> .
```
A quick guide to `cmake` [for getdns is here](https://getdnsapi.net/quick-start/cmake-quick-start/), the basics are the same for stubby but with different variables.

**Comment by trinib** [comment]
thank you
