### ISSUE TITLE
Stubby can't find libidn2 v2.3.3 due to fragility in cmake module recipe to find it. Fix for this in a pull request

### ISSUE THREAD

**Issue by jpbion** [getdnsapi/stubby#318]
libidn2 now has whitespace in its idn2.h header file where it didn't before, and this breaks the rather fragile cmake module finding 'recipe' for libidn2. I fixed this by making it a bit more robust: it allows for zero or more whitespace between "#" and "define", and one or more whitespace between "define" and "LIBIDN2_VERSION'.

I created a pull request with the necessary changes to cmake/modules/FindLibidn2.cmake to make things work in the cmake step.

**Comment by jpbion** [comment]
[stubbypatch.txt](https://github.com/getdnsapi/stubby/files/9152062/stubbypatch.txt)

**Comment by jpbion** [comment]
Here's a patch which makes stubby's search for the LibIDN2 version number a bit more robust. Works with LibIDN2 v2.3.3...
[stubby-libidn2.patch.txt](https://github.com/getdnsapi/stubby/files/9154462/stubby-libidn2.patch.txt)

**Comment by saradickinson** [comment]
Fixed by your PR: https://github.com/getdnsapi/stubby/pull/319 - thanks!
