### ISSUE TITLE
stubby.service: Failed with result 'core-dump'

### ISSUE THREAD

**Issue by Flacheisen** [getdnsapi/stubby#322]
Hello,
I've been using stubby for quite a while and it worked like a charm. After my hosting provider decided to restart the machine, I can no longer get it to work. 

stubby/focal,now 1.5.1-1build1
libc6/focal-updates,now 2.31-0ubuntu9.9 
libgetdns10/focal,now 1.5.1-1build1 
libyaml-0-2/focal,now 0.2.2-1

systemctl status stubby
```
systemd[1]: Started DNS Privacy Stub Resolver.
stubby[2908]: stubby: ./../stubby/src/yaml/convert_yaml_to_json.c:444: output_scalar: Assertion `event->data.scalar.length > 0' failed.
systemd[1]: stubby.service: Main process exited, code=dumped, status=6/ABRT
systemd[1]: stubby.service: Failed with result 'core-dump'.
```
Any ideas how to get it working again? If you need any further information, please let me know.

Thank you.

**Comment by saradickinson** [comment]
Haven't seen that before - looks like a problem processing a simple value in the config file e.g.
`edns_client_subnet_private : 1`
Do you have any parameters in the file that don't have a value? Are you able to share your config file here (or email direct to sara@sinodun.com)? 

Do you know if the restart involved any updates (a simple `apt update/upgrade` or even upgrade to focal?) Just trying to pin down what changed.

**Comment by Flacheisen** [comment]
Hey,
thank you for your answer. Your hint with the config file was helpful. The problem was a missing IP address in a manual added upstream recursive server.

I'm more than sure that I don't touched this config file in the last months and there have been some reboots in the past. So I have no clue, why this particular IP address disappeared. Other servers haven't been touched.

Quite strange, but thank you for your fast help.
