### ISSUE TITLE
Does stubby change the DNS of my WIndows WiFi NIC automatocally (or via settings)?

### ISSUE THREAD

**Issue by wellloaded** [getdnsapi/stubby#354]
I admit I'm not 100% certain this relates to Stubby but here we go:

My DNS server on the WiFi NIC always default to 127.0.0.1 (unwanted).
Everything else comes from DHCP and if I set it to anything manually related to DNS it just reverts to 127.0.0.1.

Is this something Stubby might be affecting at all?

Thanks.

**Comment by cookiemonsteruk** [comment]
Shouldn't be stubby. Where is stubby installed, your wifi client (like laptop or a device), or on what?
You say "my DNS server on the Wifi NIC". Is that a wifi router that you can modify its settings?
One usual setup is to install stubby somewhere always on, accessible in your network by ip. Then you modify your dhcp server to give the ip of the dns server, normally that is the router itself, then on the router, it needs to be configured to "forward" those queries onto stubby.

**Comment by wellloaded** [comment]
This is affecting only my windows 11 laptop e.g. my Android mobile phone works completely fine.so I would exclude the DHCP server itself.

![image](https://github.com/getdnsapi/stubby/assets/46318040/bb1fec5b-9f0b-48da-95a3-3f17331f734f)


![image](https://github.com/getdnsapi/stubby/assets/46318040/a76e7d03-bc8e-42a0-901e-1f0fb47f462c)

Stubby is installed on the Windows 11 laptop. Once again I'm not 100% certain this to be Stubby related but I'm going by exclusion and can't find anything else on my system that might affect the DNS settings.

**Comment by cookiemonsteruk** [comment]
OK. This says, don't go to the router but stay local (loopback) to resolve names. This seems to be what I would expect if you have made the OS to use stubby. I'd have to see what the instructions are for running stubby on windows. This is also what happens with default linux Ubuntu that defaults to doing its own recursion out of the box, but I can diagnose in linux, I'm not versed in windows.

**Comment by cookiemonsteruk** [comment]
checked the docs https://dnsprivacy.org/dns_privacy_daemon_-_stubby/installation/windows_installer_for_stubby/
Section:
```
Modify your upstream resolvers

Once this change is made all your DNS queries will be re-directed to Stubby and sent over TLS! 
(You may need to restart some applications to have them pick up the network settings).

For Stubby to re-send outgoing DNS queries over TLS the recursive resolvers configured on your machine must be changed to send all the local queries to the loopback interface on which Stubby is listening.
```
So yes, seems like when following the instructions, it should show the loopback as the dns resolver.

**Comment by wellloaded** [comment]
Thanks you pointed me in a direction I hadn't considered so far.

So I found the **stubby_resetdns_windows.ps1** file and tried to execute it as advised in the documentation. I tried to set first and unset after:

![image](https://github.com/getdnsapi/stubby/assets/46318040/ec0876cc-aa67-4635-a70e-91b60b6d8113)

However as you can see the Ethernet DNS is set/unset as expected but the WiFi stays on 127.0.0.1. I'm wondering what I ma doing wrong...

**Comment by wellloaded** [comment]
Also may be it's me but the copy/paste form the documentation appaers to have some unwanted characters in it?

![image](https://github.com/getdnsapi/stubby/assets/46318040/d5782803-2812-4432-90b5-40102282a15f)

**Comment by cookiemonsteruk** [comment]
right. Seems the reset doesn't reset all interfaces. Needs someone from the project to comment.

**Comment by wellloaded** [comment]
I managed to fix this completely uninstalling the NIC, and installing manually the latest Intel drivers. SO not related to Stubby but rather a Windows specific issue.

Beside this, May be it's me but the copy/paste form the documentation appears to have some unwanted characters in it?

![image](https://github.com/getdnsapi/stubby/assets/46318040/d5782803-2812-4432-90b5-40102282a15f)

**Comment by saradickinson** [comment]
Sorry about the issue with the formatting - fixed now!
