### ISSUE TITLE
Create a scheduled task for stubby on Windows

### ISSUE THREAD

**Issue by saradickinson** [getdnsapi/stubby#37]
While it would be nice to have stubby run as a service it requires some development work. As a short term work around we should create a scheduled task for Stubby.  

This can be done the following way (thanks to anonymous comment on dnsprivacy.org)

Create a stubby.bat with e.g.:
```"C:\Program Files\Stubby\stubby.exe" -C "C:\Program Files\Stubby\stubby.yml" -l```

Create a stubby.vbs to hide the cmd window with:
```Dim WinScriptHost
Set WinScriptHost = CreateObject("WScript.Shell")
WinScriptHost.Run Chr(34) & "C:\Program Files\Stubby\stubby.bat" & Chr(34), 0
Set WinScriptHost = Nothing```

Create a scheduled task and use the stubby.vbs script, run at boot. ready.
Now you should have stubby running at boot.

**Comment by Velocet** [comment]
There is no need to create a stubby.vbs to hide the window. Just run it in another user context as this will to the same.

**Comment by saradickinson** [comment]
Closing this issue as Version 0.2.0 of stubby and the latest windows installer includes a script and instructions in creating a scheduled task.  Please re-open if further updates needed.
