### ISSUE TITLE
IPv6 address incorrect?

### ISSUE THREAD

**Issue by a3020** [getdnsapi/stubby#50]
I ran the powershell script to set up the DNS, but noticed that IPv6 didn't work for me.

Maybe the address should be changed to `::1`? That did work for me, at least.

https://github.com/getdnsapi/stubby/blob/03c09470c3e1baa14bec428f5e50cd07527f1607/windows/stubby_setdns_windows.ps1#L4

**Comment by ArchangeGabriel** [comment]
It should be, but then it fails on Linux: https://github.com/getdnsapi/getdns/issues/358.

**Comment by saradickinson** [comment]
What version of Windows are you using? It works fine on Windows 10 (with extra debugging output):
```
c:\Program Files\Stubby>PowerShell -ExecutionPolicy bypass -file  "C:\Program Files\Stubby\stubby_setdns_windows.ps1"
Setting DNS servers on interface Ethernet0 to use local resolver - the system will use Stubby if it is running

InterfaceAlias               Interface Address ServerAddresses
                             Index     Family
--------------               --------- ------- ---------------
Ethernet0                            4 IPv4    {127.0.0.1}
Ethernet0                            4 IPv6    {::1}
```

**Comment by saradickinson** [comment]
I'm closing this issue as it didn't get any further info from the initial reporter and could not be reproduced. But please re-open if there is a further update.
