### ISSUE TITLE
Create aliases for Strict/Opportunistic usage profiles  in the getdns options

### ISSUE THREAD

**Issue by ArchangeGabriel** [getdnsapi/stubby#56]
https://github.com/getdnsapi/getdns/pull/366 made me wonder whether we could be able to select ciphers and curves used by stubby.

As soon as possible (i.e. when upstream resolvers support that), I would like to restrain it to:
- TLS 1.3, but at least TLS 1.2;
- The exact cipher list proposed by the above mentioned PR;
- x25519 and x448 as only available curves.

**Comment by saradickinson** [comment]
FYI - Stubby already is configured to use TLS 1.2 as the min version (as specified in https://datatracker.ietf.org/doc/draft-ietf-dprive-dtls-and-tls-profiles/) and in strict mode only the subset of cipher suites listed in RFC7525 are offered. Opportunistic mode uses the default cipher suites.

**Comment by ArchangeGabriel** [comment]
Strict mode = `tls_authentication: GETDNS_AUTHENTICATION_REQUIRED`?

**Comment by ArchangeGabriel** [comment]
Answering to myself: yes, it is. However that’s a bad naming I think, even if the documentation above in the example file says what it is about. ;)

**Comment by saradickinson** [comment]
@ArchangeGabriel completely agree the name could be better. We implemented early before the Strict vs Opportunistic spec was fully formed. @wtoorop we should consider creating aliases for these option values.... 

In fact, given the current spec (which is almost baked) this should actually be something like
tls_usage_profile: GETDNS_PRIVACY_STRICT

**Comment by saradickinson** [comment]
Ability to set cipher suites was added in https://github.com/getdnsapi/getdns/pull/367

Changing the title to reflect the remaining work - create correctly named options for Strict/Opportunistic

**Comment by ArchangeGabriel** [comment]
@saradickinson So how do I specify in stubby config file the cipher suites I want to use? And the allowed curves? I’m not sure that this specific feature, which is what I’m asking for, is available in Stubby. The aliasing of Strict/Opportunistic should be in a separated issue I think.

**Comment by ArchangeGabriel** [comment]
Note: I’m perfectly happy with the default cipher list from the Strict mode, my question is more theoretical on that point. However I do want to restrain curves to X25519 and x448.

**Comment by wtoorop** [comment]
Add a config line to your stubby.yml
```
tls_cipher_list: "TLS13-AES-256-GCM-SHA384:TLS13-AES-128-GCM-SHA256:TLS13-CHACHA20-POLY1305-SHA256:EECDH+AESGCM:EECDH+CHACHA20"
```

**Comment by ArchangeGabriel** [comment]
OK, thanks. :) So ciphers are done. What about curves? ;)

**Comment by wtoorop** [comment]
Ah... found the functions: SSL_CTX_set1_curves_list and  SSL_set1_curves_list.
Well... I'll create the config options. Pitty the semver police doesn't allow us to do a point release with just this extra config option!

**Comment by ArchangeGabriel** [comment]
And if I want to set the curves list now that this is available in `getdns` `1.4.0`, if I understand correctly there is two options:
```
tls_curves_list: "X25519"
```
globally or one such instruction per upstream (to better adjust depending on what they support)?

**Comment by wtoorop** [comment]
Correct :)

**Comment by ArchangeGabriel** [comment]
Hum, does not seem to work. I’ve set this for `dnsovertls.sinodun.com` which apparently does not support this curve, but requests are still going through.

**Comment by wtoorop** [comment]
I have to admit I have not tested, but the underlying openssl functions are called.
Maybe you have to use a combination of tls_cipher_list and tls_curves_list?
I'll give it a try myself too....

**Comment by ArchangeGabriel** [comment]
I’ve retried today and it failed normally. Not sure why it worked last time, but at least it seems resolved. And btw, yes I have `tls_cipher_list` (but globally) and `tls_curves_list` (but only per upstream currently as `sinodun.com` server do not support `X25519`).

However, I’ve noticed that curves are mentioned on their own at https://getdnsapi.net/doxygen/group__getdns__context.html#ga93e5f0540b2ab198ba908e6868cd51b6, but not in https://getdnsapi.net/doxygen/group__getdns__context.html#ga248a2a426cab71d8d12b093e487118af.

**Comment by ArchangeGabriel** [comment]
I thought I wrote this somewhere but apparently not, so here we go: setting the curve for TLS 1.3 at the same time as for TLS 1.2 does not work, in OpenSSL 1.1.1 those are finally two different paths.

Also, now that TLS 1.3 is a thing, people might want to turn stubby into a TLS 1.3 only service (e.g. https://github.com/getdnsapi/stubby/issues/130#issuecomment-435955287), and something like `tls_version_list: "TLSv1.3:TLSv1.2"` could be useful (as before, globally or per upstream).

**Comment by wtoorop** [comment]
Agree.  I'll tend to this next Monday.

**Comment by ArchangeGabriel** [comment]
Any news?

**Comment by wtoorop** [comment]
Tomorrow! Promised!

**Comment by wtoorop** [comment]
I had a good look today.  Making a tls_version_list would be somewhat involved with OpenSSL 1.1.1.
I'd rather mirror their [`SSL_CTX_set_min_proto_version()`, `SSL_CTX_set_max_proto_version()`,`SSL_CTX_get_min_proto_version()`, `SSL_CTX_get_max_proto_version()`, `SSL_set_min_proto_version()`, `SSL_set_max_proto_version()`, `SSL_get_min_proto_version()`, `SSL_get_max_proto_version()`](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_min_proto_version.html) functions.

How about something like:
```
typedef enum getdns_tls_version_t {
        GETDNS_SSL3   = 1400,
        GETDNS_TLS1   = 1401,
        GETDNS_TLS1_1 = 1402,
        GETDNS_TLS1_2 = 1403,
        GETDNS_TLS1_3 = 1404
} getdns_tls_version_t;

getdns_return_t getdns_context_set_min_tls_version(
    getdns_context *context, getdns_tls_version_t min_version);
getdns_return_t getdns_context_set_max_tls_version(
    getdns_context *context, getdns_tls_version_t min_version);
getdns_return_t getdns_context_get_min_tls_version(
    getdns_context *context, getdns_tls_version_t *min_version);
getdns_return_t getdns_context_get_max_tls_version(
    getdns_context *context, getdns_tls_version_t *min_version);
```
And corresponding possibility to configure these per upstream, ie something like:
```
{ upstream_recursive_servers:
  [ { address_data: 1.1.1.1
    , tls_auth_name: "cloudflare-dns.com"
    , min_tls_version: GETDNS_TLS1_3 } ]
}
```


B.t.w. @ArchangeGabriel Today I discovered a bug in setting the `tls_cipher_list` and `tls_curvers_list` per upstream, so this might explain why it didn't work with you before.

**Comment by ArchangeGabriel** [comment]
Min/Max seems good. Your code example uses `min_version` for max calls however, likely a mistake.

`min_tls_version` should also be configurable globally I think. ;)

And ACK about the per upstream bug, that would explain things. :)

**Comment by wtoorop** [comment]
This was all implemented, so closing ticket
