### ISSUE TITLE
add stubby to chocolatey.org package manager

### ISSUE THREAD

**Issue by donestefan** [getdnsapi/stubby#63]
Hi,
would you mind adding stubby to the chocolatey.org? It would make it much easier to keep stubby updated on windows. Chocolatey is a package manager for Windows (like apt-get or yum but for Windows). see: https://chocolatey.org/about
Thanks :)

**Comment by saradickinson** [comment]
Noted - will look into it. I know there is an existing package with the name stubby
https://chocolatey.org/packages/stubby
so will have to work around that (stubbydns?)

**Comment by donestefan** [comment]
Some ideas for alternative package names are
* getdns-stubby
* getdnsapi-stubby
* stubby-resolver

I personally like "getdns-stubby" - since it is close to your software naming scheme here on github.
But in the end it doesn't really matter, now does it?
Here are some [package naming recommendations](https://github.com/chocolatey/choco/wiki/CreatePackages#naming-your-package) from chocolatey

**Comment by banburybill** [comment]
We have submitted a package 'stubby-dns' to Chocolatey for review.

**Comment by saradickinson** [comment]
And it is now accepted: https://chocolatey.org/packages/stubby/0.2.5.0 and has the package name stubby (the previous stubby package was renamed)!

**Comment by donestefan** [comment]
This is great. I tried it and it works nicely 👍 

@banburybill: Looking at the chocolatey [package site](https://chocolatey.org/packages/stubby/0.2.5.0)... could you add a Link to the "[how to use stubby](https://dnsprivacy.org/wiki/display/DP/Windows+installer+for+Stubby#WindowsinstallerforStubby-RunStubby)" page? Maybe even to the cli after installation? I think first time users of stubby will appreciate this - since it is not obvious how to continue after installation (no gui, no start menu entry, no desktop icon, installation path is never shown... ). 

Thanks a lot for your effort!

**Comment by saradickinson** [comment]
Link added in 0.2.6 package!
