### ISSUE TITLE
No stubby PID file created

### ISSUE THREAD

**Issue by hanvinke** [getdnsapi/stubby#68]
$ cat stubby.pid
cat: stubby.pid: No such file or directory

It doesn't help when configuring:  --with-piddir=/usr/local/var/run
There is no file creation.

Now only manual creation possible with:
stubby & pidof stubby > /tmp/stubby.pid and cut/copy to /usr/local/var/run

**Comment by saradickinson** [comment]
Can you provide more detail please?
 - what OS are you using?
 - how did you build/install stubby? 
 - are you sure the user running stubby has permissions to write to the destination directory for the pid file.

**Comment by inudge** [comment]
On macOS stubby does not create a pid file.
On other OS, you could try defining the environment variable RUNSTATEDIR to point to the directory you want it to use for the pid file. That'll probably work, although I haven't tried it.

**Comment by hanvinke** [comment]
My operating system is ARCH Linux

Just followed the wiki on https://dnsprivacy.org/wiki/pages/viewpage.action?pageId=3145786

../configure --prefix=/usr/local --without-libidn --enable-stub-only --with-ssl=/usr --with-stubby --with-piddir=/usr/local/var/run

After 'make' you can check the logfile 'config.log' which is created in de build directory.

As you can see there is no creation of 'stubby.pid'. There is only one mentioning about 
runstatedir='/usr/local/var/run'

The directory /usr/local/var/run is empty
[config.log](https://github.com/getdnsapi/stubby/files/1632824/config.log)

The directory created has default only root access, but when I change to user 'stubby' and group 'stubby' access there is still no stubby.pid created after restart of systemd stubby service.

**Comment by saradickinson** [comment]
I just testing on macOS 10.12.6 and xenial and when I run stubby as a background process from the command line like this
``` sudo src/stubby -C ../stubby/stubby.yml.example -g```
 I do get a pid file in /usr/local/var/run (assuming default install).  Does this work for you? If so then systemd is probably putting the pid file somewhere else on ARCH linux because it is using a different runstatedir. You can search with for the file with
``` sudo find / -name stubby.pid```
Note that the systemd files provided with stubby are very basic...

**Comment by inudge** [comment]
Hi, Sara
I should've said 'by default' it does not create a pid file on macOS ;)
I just tried with the -g option on macOS 10.13.2 (stubby 1.3.0 installed via homebrew) & got error:
Could not write pid to "/usr/local/Cellar/stubby/0.2.1/var/run/stubby.pid": No such file or directory

**Comment by hanvinke** [comment]
@saradickinson 

Thanks for looking into this, I think the error is on my side.

I also do get a pidfile in /usr/local/var/run with '_sudo stubby -C /usr/local/etc/stubby/stubby.yml -g_' . I also did know that systemd never creates the pidfiles by itself for daemons.
The problem is that I didn't know that when using systemd as a daemon, systemd completely ignores the pidfile location. It is creating its own MainPID which you can find with:
'_systemctl show -p MainPID stubby.service_'. If you don't use Type=forking then PID files are irrelevant from a systemd perspective - and the PIDFile settings are completely ignored.

Configuring Stubby with the option '--with-piddir=' is therefore only useful when you don't intend to use it as a systemd service. Maybe something for the Wiki?

I am sorry to have kept you busy. So for me the issue can be closed. But maybe there is still a problem on MacOS. But maybe inudge is also using systemd?

**Comment by inudge** [comment]
@hanvinke 
Yep, e.g. on CoreOS but personally I'm only interested in running Stubby on macOS at the moment. 
I think on macOS Stubby normally runs as a Launchd daemon in the foreground and has no need or use for a PID file, which is how things usually work on macOS IMO.

**Comment by hanvinke** [comment]
Well, it seems that this also solves my problem with Zero DNSSEC configuration.
If the pidfile is read instead of the MainPID then it probably won't work.

**Comment by hanvinke** [comment]
If someone really wants a pid while running stubby as a systemd service, I have an example. Assumed stubby configured --with-piddir=/usr/local/var/run

stubby.service:

[Unit]
Description=stubby DNS resolver

[Service]
Type=simple
PIDFile=/usr/local/var/run/stubby.pid
User=stubby
Group=stubby
WorkingDirectory=/run/stubby
PermissionsStartOnly=true
ExecStartPre=/bin/chown stubby:stubby /usr/local/var/run
ExecStartPre=/bin/chmod 775 -R /usr/local/var/run

ExecStart=/usr/local/bin/stubby
ExecStop=/bin/kill -HUP $MAINPID

ExecStartPost=/ [whatever path to file] /stubby.sh

AmbientCapabilities=CAP_NET_BIND_SERVICE
CapabilityBoundingSet=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target_

And stubby.sh contains the following:

**#!/bin/bash**

**PID=$(systemctl show -p MainPID stubby.service 2>/dev/null | cut -d= -f2)
echo $PID > /usr/local/var/run/stubby.pid**

Now the MainPID is the same as the PIDfile.

You can check with:
_systemctl show -p MainPID stubby.service_
and
_sudo cat /usr/local/var/run/stubby.pid_

Both should be the same. For what it's worth...
