### ISSUE TITLE
typo in /Applications/StubbyManager.app/Contents/MacOS/stubby.yml

### ISSUE THREAD

**Issue by vollkommenheit** [getdnsapi/stubby#78]
In the following config that's commented out, the IP addr should be 94.130.110.185.

`# # ns1.dnsprivacy.at`
`#   - address_data: 194.130.110.185`
`#     tls_auth_name: "ns1.dnsprivacy.at"`

**Comment by wtoorop** [comment]
Thanks but this was already resolved with the merge of PR #66
