### ISSUE TITLE
Stubby crashes every 1-2 days

### ISSUE THREAD

**Issue by ghost** [getdnsapi/stubby#81]
System: RaspberryPi 3 
OS: raspbian lite stretch
picked from: buster repo
Stubby: 1.3.0

Every 1-2 Days Stubby doesn't work anymore

`systemclt status stubby` 
shows aktive and no Problems

after an
`systemctl restart stubby`

it runs for another 1-2 days, sometimes only for an hour....

**Comment by ArchangeGabriel** [comment]
They have been a lot of fixes recently in getdns regarding Stubby crashes (see https://github.com/getdnsapi/stubby/issues/61), you should either try from git or wait for the next release.

**Comment by Dionis0s** [comment]
![screenshot](https://user-images.githubusercontent.com/19575227/35975073-c3b658f6-0cdb-11e8-9af0-a32b68ccfb7e.png)
Sometimes it shows this errormessage in **systemctl status**.
After a **restart**, it runs like there are no problems

> They have been a lot of fixes recently in getdns regarding Stubby crashes (see #61), you should either try from git or wait for the next release.

Oh, that sounds great! :)

**Comment by poentodewo** [comment]
i dont have any issue my best is 2 week 4 days after power outgage this last i screen stubby i use v 1.2 from github compil on raspbian stretch
![cd26a687-51a7-4204-aa97-cd023722f8b8](https://user-images.githubusercontent.com/15877677/36076974-8ca29858-0f96-11e8-8af4-0f8bf1a29a3e.jpg)

**Comment by Dionis0s** [comment]
@poentodewo that is very strange O.o . I've tested v 1.2 bould from source, 1.2.1 from the buster repo und at least 1.3 from the buster repo. With all versions i had the same problem.

Could it be possible that my RasPi 3 is overloaded by the tor.service wich runs as a relay?
In `htop` tor only uses ~20-30% CPU capacity.

**Comment by wtoorop** [comment]
I'm about to do a candidate for the 1.4.0 release of getdns which might have your issue resolved.

**Comment by phoen7x** [comment]
This issue can be closed. 1.4.0. has solved the problem. :) :+1:
