### ISSUE TITLE
Stubby 0.2.2 running well on macOS

### ISSUE THREAD

**Issue by inudge** [getdnsapi/stubby#83]
Just wanted to say that we've been running the new Stubby version 0.2.2 since release on a handful of macOS systems (High Sierra 10.13.3) with no problems at all.

Upgrade via Homebrew was smooth. 
We're using round_robin_upstreams: 1
4 IPv4 servers (quad9.net & sinodun)  - getting very good performance
(no DNSSEC validation enabled)

the getdns_server_mon tool is very useful and much appreciated !

So a big thumbs up & thank you very much

**Comment by saradickinson** [comment]
@inudge Thanks so much for the feedback :-)
