### ISSUE TITLE
Installing stubby on Fedora 26 / Time out ?

### ISSUE THREAD

**Issue by ThierryIT** [getdnsapi/stubby#84]
Hi,

Using sys-net (Qubes 4) based on fedora-26 template, I am not able to install it:

`fatal: clone of 'git://g.blicky.net/yxml.git into submodule path ':home/user/src/getdns/src/yxml failed` 
`Failed to clone 'src/yxml'.`
`fatal: unable to connect to g.blicky.net: .... time out`

If using `nslookup` I am able to resolv this address.

Thx

**Comment by saradickinson** [comment]
Check your firewall... you need to be able to access a 'git:' repo address (not just a 'https:' address). 
Or as a workaround you can of course manually clone the repo using https...

@wtoorop is there a reason git: is used here instead of https: ?  (We have hit this issue too.)

**Comment by wtoorop** [comment]
No reason, I just copy pasted the reference to the repo.  I didn't know g.blicky.net also supported https.
I suppose it'd be best (have fewer dependencies) to have a clone in our github home and reference that like we do with the other submodules.

**Comment by saradickinson** [comment]
Closing as resolve by the above commit.
