### ISSUE TITLE
configure: error: cannot find install-sh

### ISSUE THREAD

**Issue by len-ro** [getdnsapi/stubby#88]
Documentation on the main page should include 
```
libtoolize -ci
```
otherwise the following error will result on configure:
```
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
```

Regards

**Comment by len-ro** [comment]
In fact this information exists on the getdns main page so this is not so important. Thank you.

**Comment by saradickinson** [comment]
Hi, the above command is only needed when building getdns, or when building Stubby as a submodule of getdns as noted. 
I've fixed the build instructions in the Stubby README though.
