### ISSUE TITLE
Windows - cannot install Stubby

### ISSUE THREAD

**Issue by 9837867dfdb138f20** [getdnsapi/stubby#90]
Windows 7 Ultimate: Service Pack 1
Stubby version: from day 3rd April 2018(newest right now)

What I did:

1. Downloaded windows installer from https://dnsprivacy.org/wiki/display/DP/Windows+installer+for+Stubby 
2. Installed Stubby files in Program Files
3. Opening the .bat, .exes(getdns_query - flashes something once, stubby.bat - same thing as described below, stubby.exe - "no config file found...")
4. Starting install from administrator: command prompt

C:\Users\User>"C:\Program Files\Stubby\stubby.exe" -C "C:\Program Files\Stubby\stubby.yml" -1
[19:38:27.628784] STUBBY: Read config from file C:\Program Files\Stubby\stubby.yml
[19:38:27.633784] STUBBY: Starting DAEMON....

aaand that's it, after ~20 minutes still same thing is in administrator: command prompt

I don't know how long it installs but I have feeling it doesn't working as intended, halp.

**Comment by jankal** [comment]
@9837867dfdb138f20 What you did here was just right.

This:
```
[19:38:27.633784] STUBBY: Starting DAEMON....
```
means, that Stubby started successfully and awaits requests now.
If you just want to start it without keeping your cmd open, just use the following VB-Script or add Stubby as a Sheduled Task like this:
```cmd
> schtasks /create /tn Stubby /XML "C:\Program Files\Stubby\stubby.xml" /RU <you_user_name>
```

stubby.vbs (to start in background):
```vb
Dim WinScriptHost
Set WinScriptHost = CreateObject("WScript.Shell")
WinScriptHost.Run Chr(34) & "C:\Program Files\Stubby\stubby.bat" & Chr(34), 0
Set WinScriptHost = Nothing
```
