### ISSUE TITLE
Yaml is really anti-human. A space can cause an accident!

### ISSUE THREAD

**Issue by lp123sun** [getdnsapi/stubby#94]
Yaml is really anti-human. A space can cause an accident!

https://www.zionandzion.com/json-vs-xml-vs-toml-vs-cson-vs-yaml/

Why not use json ?

**Comment by lp123sun** [comment]
resolution_type: GETDNS_RESOLUTION_STUB
dns_transport_list: GETDNS_TRANSPORT_TLS
tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
tls_query_padding_blocksize: 128
edns_client_subnet_private: 1
idle_timeout: 10000
listen_addresses: 127.0.0.1
round_robin_upstreams: 1
upstream_recursive_servers:
  - address_data: 9.9.9.9
    tls_auth_name: dns.quad9.net
    tls_pubkey_pinset:
      - digest: sha256
        value: ZMZ1T16d9Qc5uvRpUn/mu6fh4+IdoJGOEKjANut91Io=
  - address_data: 1.1.1.1
    tls_auth_name: cloudflare-dns.com
    tls_port: 853
    tls_pubkey_pinset:
      - digest: sha256
        value: yioEpqeR4WtDwE9YxNVnCEkTxIjx6EEIwFSQW+lJsbc=

, "Generic error"
Could not parse config file "C:\Program Files\Stubby\stubby.yml": Generic error

**Comment by saradickinson** [comment]
Closing, JSON is supported. This tool can be used to convert yaml to json
https://yaml-online-parser.appspot.com/
