### ISSUE TITLE
Compiling stubby with static libssl

### ISSUE THREAD

**Issue by vapniks** [getdnsapi/stubby#96]
Is it possible to compile stubby with a static libssl so that I can use an up to date version of openssl?

I'm running Ubuntu 14.04 which has openssl version 1.0.1 and doesn't do hostname authentication so I can't use strict mode:
```
ERROR: Hostname Authentication not available from TLS library (check library versi
on)
```
I can download and compile a newer version of libssl, but I don't want to risk replacing it across my system.

**Comment by wtoorop** [comment]
Yes this is possible.  This is what I do for my (personal) windows builds too.
You have to run configure from a extracted getdns tarball with the following options:
```
./configure 'CFLAGS=-DYAML_DECLARE_STATIC' LDFLAGS=-static --disable-shared  --without-libunbound --without-libidn --without-libidn2 --with-ssl=<static ssl location> --with-libyaml=<static libyaml location> --with-stubby
```
OpenSSL has a dependency on libz which you build by configuring linke this:
```
prefix=<static zlib location> ./configure --static
```

This is how I configure OpenSSL (for a static build):
```
./Configure mingw --openssldir=<static ssl location>/ssl --prefix=<static ssl location> --with-zlib-include=<static zlib location>/include  --with-zlib-lib=<static zlib localib>/libzlib-dynamic no-shared
```
And this is how to configure libyaml:
```
./configure --enable-static --disable-shared --prefix=<static libyaml location>
```

**Comment by vapniks** [comment]
Great, thanks!
I had to make a few slight changes to the openssl-1.1.1-pre4 directory after building it so that configure for getdns could find the static libs and include files. I didn't build libyaml or libz since they are already installed on my system.
For the benefit of others here are the shell commands that I ran. 
Note that I also used checkinstall to build a debian package so it can easily be uninstalled or reinstalled.
```
cd ~/Downloads/openssl-1.1.1-pre4/
./config
make
mkdir lib
cp libssl.a libcrypto.a lib/
cp include/openssl/* include/
cd ../getdns-1.4.1/
./configure 'CFLAGS=-DYAML_DECLARE_STATIC' LDFLAGS=-static --disable-shared  --without-libunbound --without-libidn --without-libidn2 --with-ssl=/home/ben/Downloads/openssl-1.1.1-pre4 --with-stubby
make
sudo checkinstall --pkgname stubby -D make install
```
