### ISSUE TITLE
upstart script for stubby

### ISSUE THREAD

**Issue by vapniks** [getdnsapi/stubby#97]
For the linux users out there, here is an upstart script for stubby;
https://gist.github.com/vapniks/2fef05310f50b3ed735c7f7d1c631686
I'm no upstart expert, but it seems to work fine (its based on the ssh upstart script).

**Comment by saradickinson** [comment]
Many thanks for this, we've added it to the contrib directory for the 0.2.3 release:
https://github.com/getdnsapi/stubby/pull/110
